# -*- coding: utf-8 -*-
"""sage_sensitivity_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UqqRMh9SolEQpORgYsc759bgN_HlfG8D
"""

"""
Sensitivity Analysis: Tornado Figure + SI Tables
Standalone code - reads parameters from sensitivity_sweeps.csv
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

SAGE_DIR = Path("/content/drive/MyDrive/SAGE")
OUTPUT_DIR = SAGE_DIR / "sensitivity_results_final"
SWEEPS_CSV = SAGE_DIR / "sensitivity_sweeps.csv"

# Units for each parameter (add new parameters here as needed)
PARAM_UNITS = {
    'sigma_manufacturing_quality': '—',
    'vertical_temp_gradient_C': '°C',
    'E_a_cal': 'J/mol',
    'E_a_cyc': 'J/mol',
    'container_baseline': '°C',
    'beta_cal': '—',
    'num_discharge_hours': 'h',
    'SoH_EOL': '—',
}

# Model-definition parameters (excluded from main tornado figure)
MODEL_DEF_PARAMS = ['SoH_EOL', 'beta_cal']

# Load sweep definitions from CSV
sweeps_df = pd.read_csv(SWEEPS_CSV)
SWEEPS = {}
for _, row in sweeps_df.iterrows():
    param = row['parameter']
    values = [float(v.strip()) for v in row['values'].split(',')]
    SWEEPS[param] = values

print(f"Loaded {len(SWEEPS)} parameters from {SWEEPS_CSV.name}")

# Load all results
results = []
for f in sorted(OUTPUT_DIR.glob("sage_fleet_lifespans_*.csv")):
    run_name = f.stem.replace("sage_fleet_lifespans_", "")
    parts = run_name.rsplit("_", 1)
    param = parts[0]
    val = float(parts[1].replace("p", "."))

    df = pd.read_csv(f)
    life = df['lifespan_years']
    results.append({
        'Parameter': param,
        'Value': val,
        'Mean (yr)': round(life.mean(), 2),
        'Std (yr)': round(life.std(), 2),
        'P10 (yr)': round(life.quantile(0.1), 2),
        'P50 (yr)': round(life.quantile(0.5), 2),
        'P90 (yr)': round(life.quantile(0.9), 2),
        'Min (yr)': round(life.min(), 2),
        'Max (yr)': round(life.max(), 2),
    })

results_df = pd.DataFrame(results).sort_values(['Parameter', 'Value'])

# Compute elasticities
elast_rows = []
for param in results_df['Parameter'].unique():
    subset = results_df[results_df['Parameter'] == param].sort_values('Value')
    x = subset['Value'].values
    y = subset['Mean (yr)'].values
    mid_idx = len(x) // 2
    x_base, y_base = x[mid_idx], y[mid_idx]
    slope = np.polyfit(x, y, 1)[0]
    elasticity = slope * (x_base / y_base) if y_base != 0 else 0
    elast_rows.append({
        'Parameter': param,
        'Baseline': x_base,
        'Elasticity': round(elasticity, 3),
        'Range (yr)': round(y.max() - y.min(), 2),
    })

elast_df = pd.DataFrame(elast_rows).sort_values('Elasticity', key=abs, ascending=False)

# =========================================================================
# TORNADO FIGURE (excluding model-definition params)
# =========================================================================
physics_df = elast_df[~elast_df['Parameter'].isin(MODEL_DEF_PARAMS)].copy()
physics_df = physics_df.sort_values('Elasticity', key=abs, ascending=True)

fig, ax = plt.subplots(figsize=(10, 6))

y_pos = np.arange(len(physics_df))
colors = ['#d62728' if e < 0 else '#2ca02c' for e in physics_df['Elasticity']]
bars = ax.barh(y_pos, physics_df['Elasticity'], color=colors, height=0.6, edgecolor='black')

ax.axvline(0, color='black', linewidth=1)
ax.set_yticks(y_pos)
ax.set_yticklabels(physics_df['Parameter'], fontsize=10)
ax.set_xlabel('Elasticity (% lifespan change / % parameter change)', fontsize=12)
ax.set_title('Parameter Sensitivity: Normalized Elasticities', fontsize=14)
ax.grid(True, axis='x', alpha=0.3)

for bar, val in zip(bars, physics_df['Elasticity']):
    x_pos = bar.get_width() + 0.02 if val >= 0 else bar.get_width() - 0.02
    ha = 'left' if val >= 0 else 'right'
    ax.text(x_pos, bar.get_y() + bar.get_height()/2, f'{val:+.2f}', va='center', ha=ha, fontsize=9)

plt.tight_layout()
plt.savefig(OUTPUT_DIR / "Fig_tornado_elasticity.png", dpi=300, bbox_inches='tight')
plt.savefig(OUTPUT_DIR / "Fig_tornado_elasticity.pdf", bbox_inches='tight')
plt.show()

print(f"Saved: Fig_tornado_elasticity.png/pdf")

# =========================================================================
# SI TABLES (comma-delimited for Excel)
# =========================================================================

print("\n" + "=" * 70)
print("TABLE S7a: Parameter Sweep Definitions")
print("=" * 70)
print("Parameter,Baseline,Sweep Values,Units")
for param, values in SWEEPS.items():
    mid_idx = len(values) // 2
    baseline = values[mid_idx]
    values_str = "; ".join([str(v) for v in values])
    units = PARAM_UNITS.get(param, '—')
    print(f"{param},{baseline},{values_str},{units}")

print("\n" + "=" * 70)
print("TABLE S7b: Full Results")
print("=" * 70)
print(results_df.to_csv(index=False))

print("=" * 70)
print("TABLE S7c: Elasticities (All Parameters)")
print("=" * 70)
print(elast_df.to_csv(index=False))

# ============================================================
# WRITE S7/S8/S9 INTO AN EXCEL WORKBOOK (3 SHEETS) — NO PASTING
# ============================================================

import numpy as np
import pandas as pd
from pathlib import Path

SAGE_DIR = Path("/content/drive/MyDrive/SAGE")
OUTDIR = SAGE_DIR / "sensitivity_results_final"
SWEEPS_CSV = SAGE_DIR / "sensitivity_sweeps.csv"
PARAMS_CSV = SAGE_DIR / "sage_params.csv"
BASELINE_FLEET = SAGE_DIR / "sage_fleet_lifespans.csv"

assert OUTDIR.exists(), f"Missing: {OUTDIR}"
assert SWEEPS_CSV.exists(), f"Missing: {SWEEPS_CSV}"
assert PARAMS_CSV.exists(), f"Missing: {PARAMS_CSV}"
assert BASELINE_FLEET.exists(), f"Missing: {BASELINE_FLEET}"

def pctl(x, q):
    return float(np.percentile(np.asarray(x, dtype=float), q))

def runname_from_filename(fname: str) -> str:
    return Path(fname).stem.replace("sage_fleet_lifespans_", "")

def parse_value_token(token: str) -> float:
    # encodes decimals like 0p02 -> 0.02
    return float(token.replace("p", "."))

def load_baseline_params(path: Path) -> dict:
    df = pd.read_csv(path)
    out = {}
    for _, r in df.iterrows():
        name = str(r["name"]).strip()
        dtype = str(r["dtype"]).strip().lower()
        if dtype in ["float", "int"]:
            out[name] = float(r["value_float"])
        elif dtype == "bool":
            out[name] = 1.0 if str(r["value_bool"]).strip().upper() == "TRUE" else 0.0
    return out

baseline_params = load_baseline_params(PARAMS_CSV)

# ----------------------------
# Table S7: sweep configurations
# ----------------------------
sweeps = pd.read_csv(SWEEPS_CSV)
rows_S7 = []
for _, r in sweeps.iterrows():
    pname = str(r["parameter"]).strip()
    base = baseline_params.get(pname, np.nan)
    values = [v.strip() for v in str(r["values"]).split(",")]
    for v in values:
        try:
            v_num = parse_value_token(v)
        except Exception:
            v_num = np.nan
        rows_S7.append({
            "Parameter": pname,
            "Baseline": base,
            "SweepValue": v_num if np.isfinite(v_num) else v
        })
table_S7 = pd.DataFrame(rows_S7).sort_values(["Parameter", "SweepValue"], kind="stable")

# ----------------------------
# Table S8: detailed fleet stats
# ----------------------------
fleet_files = sorted(OUTDIR.glob("sage_fleet_lifespans_*.csv"))
assert len(fleet_files) > 0, f"No sensitivity fleet files found in {OUTDIR}"

rows_S8 = []
for f in fleet_files:
    run = runname_from_filename(f.name)
    parts = run.split("_")
    pname = "_".join(parts[:-1])
    val = parse_value_token(parts[-1])

    df = pd.read_csv(f)
    lif = df["lifespan_years"].astype(float).values

    rows_S8.append({
        "Parameter": pname,
        "Value": val,
        "Mean": float(np.mean(lif)),
        "Std": float(np.std(lif)),
        "P10": pctl(lif, 10),
        "P50": pctl(lif, 50),
        "P90": pctl(lif, 90),
        "Min": float(np.min(lif)),
        "Max": float(np.max(lif)),
        "n": int(len(lif)),
        "source_file": f.name
    })

table_S8 = pd.DataFrame(rows_S8).sort_values(["Parameter", "Value"], kind="stable").reset_index(drop=True)

# ----------------------------
# Table S9: regression + elasticity
# ----------------------------
L0 = float(pd.read_csv(BASELINE_FLEET)["lifespan_years"].mean())

rows_S9 = []
for pname, grp in table_S8.groupby("Parameter"):
    x = grp["Value"].values.astype(float)
    y = grp["Mean"].values.astype(float)
    if len(x) < 2:
        continue

    slope, intercept = np.polyfit(x, y, 1)
    yhat = intercept + slope * x
    ss_res = float(np.sum((y - yhat) ** 2))
    ss_tot = float(np.sum((y - np.mean(y)) ** 2))
    r2 = 1.0 - ss_res / ss_tot if ss_tot > 0 else np.nan

    p0 = baseline_params.get(pname, np.nan)
    elasticity = (p0 / L0) * slope if np.isfinite(p0) else np.nan

    rows_S9.append({
        "Parameter": pname,
        "Baseline": p0,
        "Slope_dLdp": float(slope),
        "Intercept": float(intercept),
        "R2": float(r2),
        "Elasticity": float(elasticity),
        "Range_yr": float(np.max(y) - np.min(y)),
        "BaselineMeanLifespan_L0": float(L0),
        "n_points": int(len(x))
    })

table_S9 = pd.DataFrame(rows_S9).sort_values("Parameter", kind="stable").reset_index(drop=True)

# ----------------------------
# Write Excel workbook
# ----------------------------
xlsx_path = OUTDIR / "SAGE_Sensitivity_SI_Tables.xlsx"
with pd.ExcelWriter(xlsx_path, engine="openpyxl") as writer:
    table_S7.to_excel(writer, sheet_name="Table_S7", index=False)
    table_S8.to_excel(writer, sheet_name="Table_S8", index=False)
    table_S9.to_excel(writer, sheet_name="Table_S9", index=False)

# Optional: also write CSVs (Excel opens them fine)
table_S7.to_csv(OUTDIR / "Table_S7.csv", index=False, float_format="%.6f")
table_S8.to_csv(OUTDIR / "Table_S8.csv", index=False, float_format="%.6f")
table_S9.to_csv(OUTDIR / "Table_S9.csv", index=False, float_format="%.6f")

print("Wrote:")
print(" ", xlsx_path)
print(" ", OUTDIR / "Table_S7.csv")
print(" ", OUTDIR / "Table_S8.csv")
print(" ", OUTDIR / "Table_S9.csv")
print("\nOpen the .xlsx in Excel — each table is on its own sheet.")

# ============================================================
# TORNADO SUMMARY TABLE (SI)
# Columns: Parameter | Baseline (parameter value) | Elasticity | Range (yr)
# Elasticity = (p0 / L0) * slope, where slope is OLS d(mean_life)/d(parameter)
# Range (yr) = max(mean_life) - min(mean_life) across sweep values
# ============================================================

import numpy as np
import pandas as pd
from pathlib import Path

SAGE_DIR = Path("/content/drive/MyDrive/SAGE")
OUTDIR   = SAGE_DIR / "sensitivity_results_final"
PARAMS_CSV = SAGE_DIR / "sage_params.csv"
BASELINE_FLEET = SAGE_DIR / "sage_fleet_lifespans.csv"

assert OUTDIR.exists(), f"Missing: {OUTDIR}"
assert PARAMS_CSV.exists(), f"Missing: {PARAMS_CSV}"
assert BASELINE_FLEET.exists(), f"Missing: {BASELINE_FLEET}"

# ----------------------------
# Load baseline parameter values (p0) from sage_params.csv
# ----------------------------
params_df = pd.read_csv(PARAMS_CSV)

def get_baseline_param_value(name: str) -> float:
    row = params_df[params_df["name"].astype(str).str.strip() == name]
    if len(row) != 1:
        raise KeyError(f"Baseline parameter '{name}' not found uniquely in sage_params.csv")
    dtype = str(row.iloc[0]["dtype"]).strip().lower()
    if dtype in ["float", "int"]:
        return float(row.iloc[0]["value_float"])
    if dtype == "bool":
        return 1.0 if str(row.iloc[0]["value_bool"]).strip().upper() == "TRUE" else 0.0
    raise TypeError(f"Unsupported dtype for '{name}': {dtype}")

# ----------------------------
# Baseline mean lifespan L0 (for elasticity normalization)
# ----------------------------
L0 = float(pd.read_csv(BASELINE_FLEET)["lifespan_years"].mean())

# ----------------------------
# Parse sensitivity run files -> (Parameter, Value, MeanLife)
# ----------------------------
def parse_value_token(token: str) -> float:
    # encodes decimals like 0p02 -> 0.02
    return float(token.replace("p", "."))

def runname_from_filename(fname: str) -> str:
    return Path(fname).stem.replace("sage_fleet_lifespans_", "")

rows = []
fleet_files = sorted(OUTDIR.glob("sage_fleet_lifespans_*.csv"))
assert len(fleet_files) > 0, f"No sensitivity fleet files found in {OUTDIR}"

for f in fleet_files:
    run = runname_from_filename(f.name)
    parts = run.split("_")
    pname = "_".join(parts[:-1])
    pval = parse_value_token(parts[-1])

    df = pd.read_csv(f)
    mean_life = float(df["lifespan_years"].mean())

    rows.append({"Parameter": pname, "Value": pval, "MeanLife": mean_life})

df_all = pd.DataFrame(rows)

# ----------------------------
# Build summary: baseline param value p0, elasticity, range
# ----------------------------
summary = []

for pname, grp in df_all.groupby("Parameter"):
    grp = grp.sort_values("Value")
    x = grp["Value"].values.astype(float)
    y = grp["MeanLife"].values.astype(float)

    # Range in years (across sweep)
    life_range = float(np.max(y) - np.min(y))

    # Slope from OLS regression y = a + b x
    if len(x) >= 2:
        b, a = np.polyfit(x, y, 1)   # slope b = dL/dp
    else:
        b = np.nan

    # Baseline parameter value from sage_params.csv
    p0 = get_baseline_param_value(pname)

    # Elasticity at baseline: (p0/L0) * dL/dp
    elasticity = float((p0 / L0) * b) if np.isfinite(b) else np.nan

    summary.append({
        "Parameter": pname,
        "Baseline": p0,                 # <-- baseline PARAMETER VALUE (what you asked for)
        "Elasticity": elasticity,
        "Range (yr)": life_range
    })

df_summary = pd.DataFrame(summary)

# Optional: sort like a tornado table (largest impact first)
df_summary["AbsRange"] = df_summary["Range (yr)"].abs()
df_summary = df_summary.sort_values("AbsRange", ascending=False).drop(columns=["AbsRange"])

# Pretty rounding for SI
df_summary["Baseline"] = df_summary["Baseline"].map(lambda v: float(v))
df_summary["Elasticity"] = df_summary["Elasticity"].map(lambda v: float(v) if pd.notnull(v) else v)
df_summary["Range (yr)"] = df_summary["Range (yr)"].map(lambda v: float(v))

print("\nTornado summary (Parameter | Baseline param | Elasticity | Range yr)\n")
print(df_summary.round({"Baseline": 6, "Elasticity": 4, "Range (yr)": 4}).to_string(index=False))

# Save to Excel (1 sheet)
out_xlsx = OUTDIR / "SI_Tornado_Summary_Table.xlsx"
df_summary.round({"Baseline": 6, "Elasticity": 6, "Range (yr)": 6}).to_excel(out_xlsx, index=False)
print(f"\nSaved: {out_xlsx}")
print(f"\n(Elasticity uses L0={L0:.4f} yr from {BASELINE_FLEET.name})")

import platform
import psutil
import multiprocessing
import subprocess
import sys
import os

print("="*60)
print("COLAB RUNTIME INFORMATION")
print("="*60)

# Python
print("Python version:", sys.version.replace("\n", ""))
print("Python executable:", sys.executable)

# OS
print("Platform:", platform.platform())
print("Machine:", platform.machine())
print("Processor:", platform.processor())

# CPU info (Linux)
try:
    cpuinfo = subprocess.check_output("lscpu", shell=True).decode()
    print("\nCPU INFO (lscpu):")
    print(cpuinfo)
except:
    print("Could not retrieve lscpu info")

# Logical cores
print("\nLogical CPU count:", multiprocessing.cpu_count())

# RAM
mem = psutil.virtual_memory()
print("Total RAM (GB):", round(mem.total / 1e9, 2))

print("="*60)