# -*- coding: utf-8 -*-
"""sage_visualizations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16fsCmM4OqlTMjG3EyPyAwWzl2RqG0d5_
"""

"""
SAGE Visualizations: Cell 0 - Load Data
=======================================
Loads fleet data exported from SAGE.ipynb.

Run SAGE.ipynb first to generate sage_fleet_data.pkl.

CONCURRENCY SAFETY:
- Checks for sensitivity lock file before loading
- Makes a local snapshot copy to avoid mid-read corruption

Outputs
-------
fleet_summaries : list of dict
    Asset summary metrics.
fleet_monthly_histories : list of dict
    Monthly time series for each asset.
last_asset_traj_year1 : list of dict
    Year-1 trajectory for last asset.
last_asset_env_year1 : list of dict
    Year-1 environment for last asset.
last_asset_cmd_year1 : list of dict
    Year-1 commands for last asset.
env_ref : list of dict
    Full 25-year environment (for VIZ-7 calibration plots).
params : dict
    Simulation parameters.
"""

from google.colab import drive
drive.flush_and_unmount()
drive.mount('/content/drive', force_remount=True)

import pickle
import ast
import shutil
import time
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

# -------------------------------------------------------------------------
# Configuration
# -------------------------------------------------------------------------
DATA_DIR = Path("/content/drive/MyDrive/SAGE")
PICKLE_FILENAME = "sage_fleet_data.pkl"
PARAMS_FILENAME = "sage_params.csv"
LOCK_FILENAME = "sage_sensitivity.lock"

# Local snapshot directory (avoids reading while sensitivity writes)
LOCAL_CACHE = Path("/content/sage_cache")
LOCAL_CACHE.mkdir(exist_ok=True)

# -------------------------------------------------------------------------
# Helper functions - FAIL-FAST, NO DEFAULTS
# -------------------------------------------------------------------------
def hard_assert(condition, message):
    """Assert that must be true, or fail loudly."""
    if not condition:
        raise ValueError(message)

def require_param(key):
    """Get parameter value. Fails immediately if missing."""
    if key not in params:
        raise KeyError(f"MISSING PARAMETER: '{key}' not found in {PARAMS_FILENAME}")
    return params[key]

def require_global(name):
    """Get a global variable. Fails immediately if missing."""
    if name not in globals():
        raise NameError(f"MISSING GLOBAL: '{name}' not defined. Run earlier cells first.")
    return globals()[name]

def mean_last_n_valid(arr, n=12):
    """
    Mean of last n valid (non-NaN) values in array.

    Used for computing mean temperature over last 12 months of operation,
    handling assets that reached EOL at different times.
    """
    a = np.array(arr, dtype=float)
    idx = np.where(np.isfinite(a))[0]
    if len(idx) == 0:
        return np.nan
    last = idx[-1]
    return np.nanmean(a[max(0, last - n + 1):last + 1])

# -------------------------------------------------------------------------
# CONCURRENCY CHECK: Wait if sensitivity is running
# -------------------------------------------------------------------------
lock_path = DATA_DIR / LOCK_FILENAME
max_wait_seconds = 60
wait_interval = 5

if lock_path.exists():
    print(f"WARNING: Sensitivity analysis is running ({lock_path})")
    print(f"   Waiting up to {max_wait_seconds}s for it to finish...")
    waited = 0
    while lock_path.exists() and waited < max_wait_seconds:
        time.sleep(wait_interval)
        waited += wait_interval
        print(f"   Waited {waited}s...")

    if lock_path.exists():
        print(f"   Lock still present. Proceeding anyway (data may be inconsistent).")
    else:
        print(f"   Lock released. Proceeding.")

# -------------------------------------------------------------------------
# Load params FIRST (needed for validation)
# -------------------------------------------------------------------------
params_path = DATA_DIR / PARAMS_FILENAME

if not params_path.exists():
    raise FileNotFoundError(f"CRITICAL: {params_path} not found. Cannot proceed.")

# Try multiple encodings to handle special characters (e.g., degree symbol)
for encoding in ['utf-8', 'latin-1', 'cp1252', 'iso-8859-1']:
    try:
        params_df = pd.read_csv(params_path, encoding=encoding)
        print(f"   Loaded params with encoding: {encoding}")
        break
    except UnicodeDecodeError:
        continue
else:
    raise ValueError(f"Could not read {params_path} with any standard encoding")

params = {}
for _, row in params_df.iterrows():
    name = row["name"]
    dtype = str(row["dtype"]).strip()
    if dtype == "float":
        params[name] = float(row["value_float"])
    elif dtype == "int":
        params[name] = int(row["value_float"])
    elif dtype == "bool":
        params[name] = str(row["value_bool"]).strip().upper() == "TRUE"
    elif dtype == "list":
        raw = row["value_list"]
        try:
            params[name] = ast.literal_eval(str(raw))
        except:
            try:
                items = [x.strip() for x in str(raw).split(",")]
                parsed = []
                for item in items:
                    try:
                        parsed.append(int(item))
                    except ValueError:
                        try:
                            parsed.append(float(item))
                        except ValueError:
                            parsed.append(item)
                params[name] = parsed
            except:
                raise ValueError(f"Failed to parse list parameter '{name}': {raw}")
print(f"   Loaded {len(params)} parameters from {params_path.name}")

# -------------------------------------------------------------------------
# SNAPSHOT: Copy pickle to local cache before loading
# -------------------------------------------------------------------------
pickle_path = DATA_DIR / PICKLE_FILENAME

if not pickle_path.exists():
    raise FileNotFoundError(
        f"Pickle file not found: {pickle_path}\n"
        f"Run SAGE.ipynb first to generate this file."
    )

# Copy to local cache to avoid reading while sensitivity writes
local_pickle = LOCAL_CACHE / PICKLE_FILENAME
shutil.copy(pickle_path, local_pickle)
print(f"   Snapshot copied to: {local_pickle}")

# -------------------------------------------------------------------------
# Load pickle data from LOCAL SNAPSHOT
# -------------------------------------------------------------------------
with open(local_pickle, "rb") as f:
    data = pickle.load(f)

# Validate required keys - NO FALLBACKS
required_keys = ["fleet_summaries", "fleet_monthly_histories",
                 "last_asset_traj_export", "last_asset_env_export",
                 "last_asset_cmd_export", "env_ref"]

for key in required_keys:
    hard_assert(key in data,
        f"MISSING: '{key}' not in pickle file. Re-run SAGE.ipynb with updated Cell 25.")

fleet_summaries = data["fleet_summaries"]
fleet_monthly_histories = data["fleet_monthly_histories"]
last_asset_traj_year1 = data["last_asset_traj_export"]
last_asset_env_year1 = data["last_asset_env_export"]
last_asset_cmd_year1 = data["last_asset_cmd_export"]
env_ref = data["env_ref"]

print(f"Cell 0: Loaded {len(fleet_summaries)} assets + {len(env_ref):,} hours env_ref from {pickle_path.name}")
print(f"   Year-1 data: {len(last_asset_traj_year1)} hours")

# -------------------------------------------------------------------------
# Load visualization parameters - FAIL IF MISSING
# -------------------------------------------------------------------------
VIZ_PARAMS = {
    'spike_threshold_multiplier': require_param("viz_spike_threshold_multiplier"),
    'lifespan_cap': require_param("viz_lifespan_cap"),
    'cohort_high_pct': require_param("viz_cohort_high_percentile"),
    'cohort_low_pct': require_param("viz_cohort_low_percentile"),
    'position_high': require_param("viz_position_threshold_high"),
    'position_low': require_param("viz_position_threshold_low"),
    'loglog_exclude_years': require_param("viz_loglog_exclude_years"),
    'sqrt_exclude_years': require_param("viz_sqrt_exclude_years"),
    'hill_k_min': int(require_param("viz_hill_k_min")),
    'hill_k_max': int(require_param("viz_hill_k_max")),
    'hill_k_step': int(require_param("viz_hill_k_step")),
    'efficiency_clip_min': require_param("viz_efficiency_clip_min"),
    'efficiency_clip_max': require_param("viz_efficiency_clip_max"),
    'revenue_display_start_year': int(require_param("viz_revenue_display_start_year")),
}

print(f"   Loaded {len(VIZ_PARAMS)} visualization parameters")

# -------------------------------------------------------------------------
# Plot styling
# -------------------------------------------------------------------------
plt.rcParams.update({
    "font.size": 10,
    "axes.labelsize": 11,
    "axes.titlesize": 12,
    "figure.dpi": 150,
    "savefig.dpi": 300,
    "savefig.bbox": "tight",
})

# -------------------------------------------------------------------------
# Export key paths for other cells
# -------------------------------------------------------------------------
PARAMS_FILE = params_path  # Path object, not string
OUTPUT_DIR = DATA_DIR      # For saving figures

print("   Ready for VIZ cells.")

# Cell VIZ-1: Degradation Physics Validation Figure 3
# -----------------------------------------------------
# Validates: SoH trajectory, calendar vs cycle aging, beta exponent extraction,
#            sqrt(t) behavior against both clock time and stress-weighted effective time

import matplotlib.pyplot as plt
import numpy as np
from scipy import stats

print("VIZ-1: Generating degradation physics plots...")

hard_assert('fleet_monthly_histories' in dir(), "Run Cell 0 first")
hard_assert('fleet_summaries' in dir(), "Run Cell 0 first")
hard_assert(len(fleet_monthly_histories) > 0, "No fleet data available")

# Get configured beta from params
beta_configured = require_param("beta_cal")
print(f"   Configured beta_cal: {beta_configured}")

# Get visualization parameters
loglog_exclude_years = VIZ_PARAMS['loglog_exclude_years']
sqrt_exclude_years = VIZ_PARAMS['sqrt_exclude_years']

# Use first asset for detailed trajectory
asset_0_monthly = fleet_monthly_histories[0]
asset_0_summary = fleet_summaries[0]

months = np.arange(len(asset_0_monthly['monthly_soh_history']))
years = months / 12.0

soh = np.array(asset_0_monthly['monthly_soh_history'])
qcal = np.array(asset_0_monthly['monthly_qcal_history'])
qcyc = np.array(asset_0_monthly['monthly_qcyc_history'])

# Get cumulative_kwh for FEC calculation
cumulative_kwh = np.array(asset_0_monthly['monthly_cumulative_kwh_history'])

# Filter out NaN values
valid = ~np.isnan(soh) & ~np.isnan(qcal) & ~np.isnan(qcyc)
months_valid = months[valid]
years_valid = years[valid]
soh_valid = soh[valid]
qcal_valid = qcal[valid]
qcyc_valid = qcyc[valid]
cumulative_kwh_valid = cumulative_kwh[valid]

# Compute effective time from q_cal using configured k_cal and beta
# q_cal = k_cal * t_eff^beta  =>  t_eff = (q_cal / k_cal)^(1/beta)
k_cal = require_param("k_cal")
t_formation = require_param("t_formation_hours")
soh_eol = require_param("SoH_EOL")

# Reconstruct t_eff from q_cal (this is what the physics engine computed)
# Note: q_cal in output is already net of formation, so we need to add it back
q_cal_absolute = qcal_valid + k_cal * (t_formation ** beta_configured)
t_eff_reconstructed = (q_cal_absolute / k_cal) ** (1.0 / beta_configured)
# Convert to years for plotting
t_eff_years = t_eff_reconstructed / 8760.0

fig, axes = plt.subplots(2, 3, figsize=(15, 10))

# =============================================================================
# Plot 1: SoH vs Time
# =============================================================================
ax1 = axes[0, 0]
ax1.plot(years_valid, soh_valid, 'b-', linewidth=2, label='SoH')
ax1.axhline(y=soh_eol, color='r', linestyle='--', label='EOL Threshold')
ax1.set_xlabel('Years')
ax1.set_ylabel('State of Health')
ax1.set_title('SoH Degradation Trajectory')
ax1.legend()
ax1.grid(True, alpha=0.3)
ax1.set_ylim([0.6, 1.02])

# =============================================================================
# Plot 2: Calendar vs Cycle Aging Decomposition
# =============================================================================
ax2 = axes[0, 1]
ax2.stackplot(years_valid, qcal_valid, qcyc_valid,
              labels=['Calendar (q_cal)', 'Cycle (q_cyc)'],
              colors=['#ff7f0e', '#2ca02c'], alpha=0.7)
ax2.set_xlabel('Years')
ax2.set_ylabel('Capacity Loss Fraction')
ax2.set_title('Aging Mechanism Decomposition')
ax2.legend(loc='upper left')
ax2.grid(True, alpha=0.3)

# =============================================================================
# Plot 3: Exponent Extraction via Log-Log Regression
# =============================================================================
ax3 = axes[0, 2]

# Exclude early transient and zero/negative values - USING PARAM
mask_loglog = (years_valid > loglog_exclude_years) & (qcal_valid > 1e-9)
years_log = years_valid[mask_loglog]
qcal_log = qcal_valid[mask_loglog]

if len(years_log) > 10:
    log_t = np.log(years_log)
    log_qcal = np.log(qcal_log)

    # Linear regression on log-log data
    slope, intercept, r_value, p_value, std_err = stats.linregress(log_t, log_qcal)
    beta_fit = slope
    k_fit_annual = np.exp(intercept)  # k in units of 1/year^beta
    r_squared = r_value ** 2

    # 95% confidence interval for slope (beta)
    n = len(log_t)
    t_crit = stats.t.ppf(0.975, n - 2)
    beta_ci = t_crit * std_err

    # Plot data and fit
    ax3.scatter(log_t, log_qcal, alpha=0.5, s=15, label='Data', color='blue')
    log_t_fit = np.linspace(log_t.min(), log_t.max(), 100)
    ax3.plot(log_t_fit, intercept + slope * log_t_fit, 'r-', linewidth=2,
             label=f'Fit: beta = {beta_fit:.3f} +/- {beta_ci:.3f}')
    ax3.axhline(y=intercept + slope * 0, color='gray', linestyle=':', alpha=0.5)

    ax3.set_xlabel('ln(Years)')
    ax3.set_ylabel('ln(q_cal)')
    ax3.set_title(f'Exponent Extraction: beta_fit = {beta_fit:.3f} (R² = {r_squared:.4f})')
    ax3.legend()
    ax3.grid(True, alpha=0.3)

    # Store for summary
    beta_extraction_results = {
        'beta_fit': beta_fit,
        'beta_ci': beta_ci,
        'r_squared': r_squared,
        'beta_configured': beta_configured,
        'match': abs(beta_fit - beta_configured) < 2 * beta_ci
    }
else:
    ax3.text(0.5, 0.5, 'Insufficient data for\nlog-log regression',
             ha='center', va='center', transform=ax3.transAxes, fontsize=12)
    beta_extraction_results = None

# =============================================================================
# Plot 4: q_cal vs sqrt(t) (Clock Time) - Original Validation
# =============================================================================
ax4 = axes[1, 0]
sqrt_years_valid = np.sqrt(years_valid)

ax4.scatter(sqrt_years_valid, qcal_valid, alpha=0.5, s=10, label='q_cal data', color='blue')

# Fit through origin (assuming beta = 0.5) - USING PARAM
mask_fit = years_valid > sqrt_exclude_years
if np.sum(mask_fit) > 5:
    sqrt_t_fit = sqrt_years_valid[mask_fit]
    qcal_fit = qcal_valid[mask_fit]
    slope_sqrt = np.sum(qcal_fit * sqrt_t_fit) / np.sum(sqrt_t_fit ** 2)

    # R2 for this fit
    qcal_pred = slope_sqrt * sqrt_years_valid[mask_fit]
    ss_res = np.sum((qcal_fit - qcal_pred) ** 2)
    ss_tot = np.sum((qcal_fit - np.mean(qcal_fit)) ** 2)
    r2_sqrt = 1 - ss_res / ss_tot if ss_tot > 0 else 0

    ax4.plot(sqrt_years_valid, slope_sqrt * sqrt_years_valid, 'r-', linewidth=2,
             label=f'sqrt(t) fit (R² = {r2_sqrt:.3f})')

    # Highlight systematic deviation
    residuals_sqrt = qcal_valid - slope_sqrt * sqrt_years_valid

ax4.set_xlabel('sqrt(Years) - Clock Time')
ax4.set_ylabel('Calendar Aging (q_cal)')
ax4.set_title('q_cal vs sqrt(t_clock) (Tests Uniform Stress)')
ax4.legend()
ax4.grid(True, alpha=0.3)

# =============================================================================
# Plot 5: q_cal vs sqrt(t_eff) (Stress-Weighted Time) - Internal Consistency
# =============================================================================
ax5 = axes[1, 1]
sqrt_t_eff = np.sqrt(t_eff_years)

ax5.scatter(sqrt_t_eff, qcal_valid, alpha=0.5, s=10, label='q_cal data', color='green')

# This SHOULD be perfectly linear if the model is internally consistent - USING PARAM
mask_teff = t_eff_years > sqrt_exclude_years
if np.sum(mask_teff) > 5:
    sqrt_teff_fit = sqrt_t_eff[mask_teff]
    qcal_teff_fit = qcal_valid[mask_teff]
    slope_teff = np.sum(qcal_teff_fit * sqrt_teff_fit) / np.sum(sqrt_teff_fit ** 2)

    qcal_pred_teff = slope_teff * sqrt_teff_fit
    ss_res_teff = np.sum((qcal_teff_fit - qcal_pred_teff) ** 2)
    ss_tot_teff = np.sum((qcal_teff_fit - np.mean(qcal_teff_fit)) ** 2)
    r2_teff = 1 - ss_res_teff / ss_tot_teff if ss_tot_teff > 0 else 0

    ax5.plot(sqrt_t_eff, slope_teff * sqrt_t_eff, 'r-', linewidth=2,
             label=f'sqrt(t_eff) fit (R² = {r2_teff:.4f})')

ax5.set_xlabel('sqrt(t_eff) - Stress-Weighted Years')
ax5.set_ylabel('Calendar Aging (q_cal)')
ax5.set_title('q_cal vs sqrt(t_eff) (Tests Model Consistency)')
ax5.legend()
ax5.grid(True, alpha=0.3)

# =============================================================================
# Plot 6: Stress Acceleration Factor (t_eff / t_clock)
# =============================================================================
ax6 = axes[1, 2]

# Compute instantaneous stress factor as ratio of effective to clock time - USING PARAM
stress_ratio = t_eff_years / years_valid
# Handle division issues at t=0
stress_ratio[years_valid < sqrt_exclude_years] = np.nan

ax6.plot(years_valid, stress_ratio, 'purple', linewidth=2)
ax6.axhline(y=1.0, color='gray', linestyle='--', label='No stress acceleration')
ax6.set_xlabel('Years (Clock Time)')
ax6.set_ylabel('t_eff / t_clock')
ax6.set_title('Cumulative Stress Acceleration Factor')
ax6.legend()
ax6.grid(True, alpha=0.3)

# Add annotation for interpretation
mean_stress = np.nanmean(stress_ratio[years_valid > 1])
ax6.text(0.95, 0.95, f'Mean: {mean_stress:.2f}x', transform=ax6.transAxes,
         ha='right', va='top', fontsize=11,
         bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

plt.tight_layout()
plt.savefig('viz1_degradation_physics.png', dpi=150, bbox_inches='tight')
plt.show()

# =============================================================================
# Summary Statistics
# =============================================================================
print(f"\n{'='*60}")
print("DEGRADATION PHYSICS VALIDATION SUMMARY")
print(f"{'='*60}")

print(f"\nVisualization Parameters Used:")
print(f"   loglog_exclude_years: {loglog_exclude_years}")
print(f"   sqrt_exclude_years: {sqrt_exclude_years}")

print(f"\nAsset 0 Trajectory:")
print(f"   Duration: {years_valid[-1]:.1f} years ({len(years_valid)} months)")
print(f"   Initial SoH: {soh_valid[0]:.4f}")
print(f"   Final SoH:   {soh_valid[-1]:.4f}")
print(f"   Total q_loss: {(qcal_valid[-1] + qcyc_valid[-1]):.4f}")

print(f"\nAging Mechanism Split (at EOL):")
pct_cal = 100 * qcal_valid[-1] / (qcal_valid[-1] + qcyc_valid[-1])
pct_cyc = 100 - pct_cal
print(f"   Calendar: {qcal_valid[-1]:.4f} ({pct_cal:.1f}%)")
print(f"   Cycle:    {qcyc_valid[-1]:.4f} ({pct_cyc:.1f}%)")

print(f"\nExponent Validation:")
print(f"   Configured beta_cal: {beta_configured}")
if beta_extraction_results:
    print(f"   Extracted beta_fit:  {beta_extraction_results['beta_fit']:.4f} +/- {beta_extraction_results['beta_ci']:.4f} (95% CI)")
    print(f"   Log-log R²:       {beta_extraction_results['r_squared']:.4f}")
    if beta_extraction_results['match']:
        print(f"   PASS: beta_fit matches configured value within 2 sigma")
    else:
        delta = beta_extraction_results['beta_fit'] - beta_configured
        print(f"   DEVIATION: beta_fit differs by {delta:+.4f} from configured")

print(f"\nsqrt(t) Fit Quality:")
print(f"   Against clock time (t):     R² = {r2_sqrt:.4f}")
print(f"   Against effective time (t_eff): R² = {r2_teff:.4f}")
if r2_teff > 0.999:
    print(f"   Internal consistency confirmed (R² > 0.999 for t_eff)")
if r2_sqrt < r2_teff - 0.01:
    print(f"   -> Gap indicates non-uniform stress conditions over simulation")

print(f"\nStress Acceleration:")
print(f"   Mean t_eff/t_clock: {mean_stress:.3f}x")
if mean_stress > 1.05:
    print(f"   -> Operating conditions are {100*(mean_stress-1):.0f}% more stressful than reference")
elif mean_stress < 0.95:
    print(f"   -> Operating conditions are {100*(1-mean_stress):.0f}% less stressful than reference")
else:
    print(f"   -> Operating conditions approximately match reference (T_ref, SoC_ref)")

print(f"\n{'='*60}")



# Cell VIZ-2: Thermal Model Validation (Fixed) figure 5
# ---------------------------------------------
# Validates: Rack position thermal gradient, Arrhenius effect on lifespan
#
# FIX: Left panel now uses Year 1 mean temperature (common calendar window)
# instead of "last 12 valid months" which created seasonal cohorting artifacts.

import matplotlib.pyplot as plt
import numpy as np

print("VIZ-2: Generating thermal model plots...")

hard_assert('fleet_summaries' in dir(), "Run Cell 0 first")
hard_assert('fleet_monthly_histories' in dir(), "Run Cell 0 first")

sim_years = int(require_param("simulation_years"))

# Initialize regression coefficients (prevents crash if <3 valid points)
z_pos = np.array([np.nan, np.nan])
z_arr = np.array([np.nan, np.nan])

# -----------------------------------------------------------------------------
# LEFT PANEL: Use Year 1 mean (months 0-11) for ALL assets
# This eliminates seasonal cohorting from different retirement months
# -----------------------------------------------------------------------------
mean_T_year1 = np.array([
    np.nanmean(h['monthly_T_cell_mean_history'][:12])
    for h in fleet_monthly_histories
])

# -----------------------------------------------------------------------------
# RIGHT PANEL: Keep "last 12 months" for Arrhenius plot (lifespan on y-axis)
# The seasonal artifact doesn't create banding when y is lifespan
# -----------------------------------------------------------------------------
mean_T_last12 = np.array([
    mean_last_n_valid(h['monthly_T_cell_mean_history'], 12)
    for h in fleet_monthly_histories
])

vertical_pos = np.array([s['vertical_pos'] for s in fleet_summaries])
lifespan_years = np.array([s['lifespan_years'] for s in fleet_summaries])

valid_T_year1 = ~np.isnan(mean_T_year1)
valid_T_last12 = ~np.isnan(mean_T_last12)
censored = lifespan_years >= sim_years - 0.1
not_censored = ~censored

fig, axes = plt.subplots(1, 2, figsize=(12, 5))

# Plot 1: Position vs Temperature (Year 1 mean - common window for all assets)
ax1 = axes[0]
ax1.scatter(vertical_pos[valid_T_year1], mean_T_year1[valid_T_year1], alpha=0.6, s=30)
ax1.set_xlabel('Vertical Position (0=bottom, 1=top)')
ax1.set_ylabel('Mean T_cell Year 1 (°C)')
ax1.set_title('Rack Position vs Temperature (Year 1)')
ax1.grid(True, alpha=0.3)

if np.sum(valid_T_year1) > 2:
    z_pos = np.polyfit(vertical_pos[valid_T_year1], mean_T_year1[valid_T_year1], 1)
    ax1.plot([0, 1], [z_pos[1], z_pos[0] + z_pos[1]], 'r-', linewidth=2,
             label=f'Slope: {z_pos[0]:.2f} °C/unit')
    ax1.legend()

# Plot 2: Temperature vs Lifespan (last 12 months - unchanged)
ax2 = axes[1]
mask_eol = valid_T_last12 & not_censored
mask_censored = valid_T_last12 & censored

# Plot assets that reached EOL
ax2.scatter(mean_T_last12[mask_eol], lifespan_years[mask_eol],
            alpha=0.6, s=30, color='green', label='Reached EOL')
# Plot censored assets (survived full simulation)
if np.sum(mask_censored) > 0:
    ax2.scatter(mean_T_last12[mask_censored], lifespan_years[mask_censored],
                alpha=0.6, s=30, color='orange', marker='^',
                label=f'Censored (>{sim_years-1} yr)')

ax2.set_xlabel('Mean T_cell Last 12 Months (°C)')
ax2.set_ylabel('Lifespan (Years)')
ax2.set_title('Temperature vs Lifespan (Arrhenius Effect)')
ax2.grid(True, alpha=0.3)

# Fit only uncensored assets
if np.sum(mask_eol) > 2:
    z_arr = np.polyfit(mean_T_last12[mask_eol], lifespan_years[mask_eol], 1)
    x_fit = np.linspace(np.nanmin(mean_T_last12[valid_T_last12]),
                        np.nanmax(mean_T_last12[valid_T_last12]), 100)
    ax2.plot(x_fit, np.polyval(z_arr, x_fit), 'r-', linewidth=2,
             label=f'Slope: {z_arr[0]:.2f} yr/°C (EOL only)')
    ax2.legend()
else:
    ax2.legend()

plt.tight_layout()
plt.savefig('viz2_thermal_model.png', dpi=150, bbox_inches='tight')
plt.show()

# Summary statistics
n_censored = np.sum(mask_censored)
n_eol = np.sum(mask_eol)
print(f"\nThermal Summary (Fleet):")
print(f"   Assets reaching EOL: {n_eol}")
print(f"   Assets censored (>{sim_years-1} yr): {n_censored}")
print(f"   Year 1 T_cell: median={np.nanmedian(mean_T_year1):.2f}°C, "
      f"range=[{np.nanmin(mean_T_year1):.2f}, {np.nanmax(mean_T_year1):.2f}]")
if np.isfinite(z_pos[0]):
    print(f"   Position gradient (Year 1): {z_pos[0]:.2f} °C/unit")
else:
    print("   Position gradient (Year 1): n/a (insufficient valid points)")
if np.isfinite(z_arr[0]):
    print(f"   Arrhenius effect: {z_arr[0]:.2f} yr/°C (excluding censored)")
else:
    print("   Arrhenius effect: n/a (insufficient EOL assets)")
print(f"Points being plotted on right panel: {np.sum(mask_eol)}")

# Cell VIZ-3: Dispatch Validation + Electro-Thermal Coupling Figure 2
# ---------------------------------------------------------
# Validates: Block placement, price-following behavior, electro-thermal coupling

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

print("VIZ-3: Generating dispatch and electro-thermal coupling plots...")

hard_assert(last_asset_env_year1 is not None, "Run Cell 0 first")
hard_assert(last_asset_cmd_year1 is not None, "Run Cell 0 first")
hard_assert(last_asset_traj_year1 is not None, "Run Cell 0 first")

# Get physics parameters for efficiency calculation
eta_dis_bol = require_param("eta_discharge_bol")
eta_dis_eol = require_param("eta_discharge_eol")
soh_eol = require_param("SoH_EOL")

# Get visualization parameters
efficiency_clip_min = VIZ_PARAMS['efficiency_clip_min']
efficiency_clip_max = VIZ_PARAMS['efficiency_clip_max']

# Extract data for dispatch analysis (using environment/command data)
n = min(len(last_asset_env_year1), len(last_asset_cmd_year1), len(last_asset_traj_year1))
timestamps = [env['t_timestamp'] for env in last_asset_env_year1[:n]]
p_market = np.array([env['p_market'] for env in last_asset_env_year1[:n]])
P_cmd = np.array([cmd['P_dispatch_kw'] for cmd in last_asset_cmd_year1[:n]])

# Create DataFrame for easier analysis
df = pd.DataFrame({
    'timestamp': timestamps,
    'p_market': p_market,
    'P_cmd': P_cmd,
})
df['hour'] = pd.to_datetime(df['timestamp']).dt.hour
df['month'] = pd.to_datetime(df['timestamp']).dt.month
df['is_dispatch'] = df['P_cmd'] > 0

fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# Plot 1: Average price and dispatch probability by hour of day
ax1 = axes[0, 0]
hourly_price = df.groupby('hour')['p_market'].mean()
hourly_dispatch = df.groupby('hour')['is_dispatch'].mean()

ax1_twin = ax1.twinx()
bars = ax1.bar(hourly_price.index, hourly_price.values, alpha=0.6, color='blue', label='Avg Price')
line = ax1_twin.plot(hourly_dispatch.index, hourly_dispatch.values * 100, 'r-o',
                      linewidth=2, markersize=6, label='Dispatch %')
ax1.set_xlabel('Hour of Day')
ax1.set_ylabel('Average Price ($/MWh)', color='blue')
ax1_twin.set_ylabel('Dispatch Probability (%)', color='red')
ax1.set_title('Price Profile vs Dispatch Timing')
ax1.set_xticks(range(0, 24, 3))
ax1.grid(True, alpha=0.3)

# Plot 2: Dispatch heatmap (hour vs month)
ax2 = axes[0, 1]
dispatch_heatmap = df.pivot_table(values='is_dispatch', index='hour', columns='month', aggfunc='mean')
im = ax2.imshow(dispatch_heatmap.values, aspect='auto', cmap='YlOrRd', origin='lower')
ax2.set_xlabel('Month')
ax2.set_ylabel('Hour of Day')
ax2.set_title('Dispatch Probability Heatmap')
ax2.set_xticks(range(12))
ax2.set_xticklabels(range(1, 13))
ax2.set_yticks(range(0, 24, 4))
cbar = plt.colorbar(im, ax=ax2)
cbar.set_label('Dispatch Probability')

# Plot 3: Price distribution (dispatch vs non-dispatch hours) - LOG Y-AXIS
ax3 = axes[1, 0]
prices_dispatch = df[df['is_dispatch']]['p_market']
prices_idle = df[~df['is_dispatch']]['p_market']

bins = np.linspace(0, max(prices_idle.max(), prices_dispatch.max()), 100)

ax3.hist(prices_idle, bins=bins, alpha=0.6, label=f'Idle hours (n={len(prices_idle)})', density=True)
ax3.hist(prices_dispatch, bins=bins, alpha=0.6, label=f'Dispatch hours (n={len(prices_dispatch)})', density=True)
ax3.axvline(prices_idle.median(), color='blue', linestyle='--', linewidth=2)
ax3.axvline(prices_dispatch.median(), color='orange', linestyle='--', linewidth=2)
ax3.set_yscale('log')
ax3.set_xlabel('Market Price ($/MWh)')
ax3.set_ylabel('Density (log scale)')
ax3.set_title('Price Distribution: When We Dispatch vs Idle')
ax3.legend()
ax3.grid(True, alpha=0.3)

# Plot 4: Electro-thermal coupling validation (single representative asset)
ax4 = axes[1, 1]

# Helper: fetch a field from trajectory list - NO FALLBACKS
def get_series(traj_list, key):
    if key in traj_list[0]:
        return np.array([row[key] for row in traj_list[:n]], dtype=float)
    return None

# Get SoH - try common key names, FAIL if not found
SoH = get_series(last_asset_traj_year1, "soh_true")
if SoH is None:
    SoH = get_series(last_asset_traj_year1, "SoH")
hard_assert(SoH is not None,
    "MISSING: 'soh_true' or 'SoH' not in trajectory data. "
    "Check SAGE physics export in Cell 25.")

# Get T_cell - FAIL if not found (NO FALLBACK to T_ambient)
T_cell = get_series(last_asset_traj_year1, "T_cell")
if T_cell is None:
    T_cell = get_series(last_asset_traj_year1, "T_cell_C")
hard_assert(T_cell is not None,
    "MISSING: 'T_cell' or 'T_cell_C' not in trajectory data. "
    "Check SAGE physics export in Cell 25.")

# Get efficiency - try to load from trajectory first
eta_dis = get_series(last_asset_traj_year1, "eta_dis")
if eta_dis is None:
    eta_dis = get_series(last_asset_traj_year1, "eta_discharge")

# If efficiency not stored, compute from physics parameters (not a fallback - uses CSV values)
if eta_dis is None:
    print("   Note: eta_dis not in trajectory, computing from SoH using physics params")
    deg_progress = np.clip((1.0 - SoH) / (1.0 - soh_eol), 0.0, 1.0)
    eta_dis = eta_dis_bol - (eta_dis_bol - eta_dis_eol) * deg_progress
    eta_dis = np.clip(eta_dis, efficiency_clip_min, efficiency_clip_max)

# Compute heat generation proxy during dispatch:
# Q_heat ~ P_out * (1/eta - 1)  (units: kW of losses if P_cmd is kW)
P_out_kw = np.maximum(P_cmd[:n], 0.0)
Q_heat_kw = P_out_kw * (1.0 / eta_dis - 1.0)

# Time axis in days
t_days = np.arange(n) / 24.0

# Plot temperature on primary axis
color_temp = 'tab:blue'
ax4.plot(t_days, T_cell, color=color_temp, linewidth=1.0, alpha=0.8)
ax4.set_xlabel("Time (days)")
ax4.set_ylabel("Cell temperature (°C)", color=color_temp)
ax4.tick_params(axis='y', labelcolor=color_temp)
ax4.set_title("Electro-thermal coupling (representative asset)")
ax4.grid(True, alpha=0.3)

# Add secondary axis for heat generation proxy
ax4b = ax4.twinx()
color_heat = 'tab:orange'
ax4b.plot(t_days, Q_heat_kw, color=color_heat, linestyle="--", linewidth=1.0, alpha=0.8)
ax4b.set_ylabel("Heat generation proxy (kW loss)", color=color_heat)
ax4b.tick_params(axis='y', labelcolor=color_heat)

# Shade dispatch periods for visual context
dispatch_mask = (P_out_kw > 0)
if dispatch_mask.any():
    # Get current y-limits after plotting
    ylim = ax4.get_ylim()
    ax4.fill_between(t_days, ylim[0], ylim[1],
                     where=dispatch_mask, alpha=0.08, color='gray',
                     label='Dispatch periods')
    ax4.set_ylim(ylim)  # Restore limits after fill_between

plt.tight_layout()
plt.savefig('viz3_dispatch_coupling.png', dpi=150, bbox_inches='tight')
plt.show()

# Print summary statistics (dispatch only, no revenue)
print(f"\nDispatch Summary:")
print(f"   Total dispatch hours: {df['is_dispatch'].sum()} ({100*df['is_dispatch'].mean():.1f}%)")
print(f"   Median price when dispatching: ${prices_dispatch.median():.2f}/MWh")
print(f"   Median price when idle: ${prices_idle.median():.2f}/MWh")
print(f"   Price premium captured: ${prices_dispatch.median() - prices_idle.median():.2f}/MWh")

print(f"\nElectro-thermal Coupling (Year 1):")
print(f"   Temperature range: [{T_cell.min():.1f}, {T_cell.max():.1f}] °C")
print(f"   Mean temperature: {np.mean(T_cell):.1f} °C")
print(f"   Max heat generation: {Q_heat_kw.max():.1f} kW")
print(f"   SoH range: [{SoH.min():.4f}, {SoH.max():.4f}]")

print(f"\nParameters Used:")
print(f"   eta_discharge_bol: {eta_dis_bol}")
print(f"   eta_discharge_eol: {eta_dis_eol}")
print(f"   SoH_EOL: {soh_eol}")
print(f"   efficiency_clip_min: {efficiency_clip_min}")
print(f"   efficiency_clip_max: {efficiency_clip_max}")

# Cell VIZ-3b: Figure 4 for Joule - Fleet Revenue Divergence
# ----------------------------------------------------------
# Clean 1-panel figure showing cumulative revenue divergence

import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path

print("VIZ-3b: Generating Figure 4 (Fleet Revenue Divergence)...")

hard_assert('fleet_summaries' in dir(), "Run Cell 0 first")
hard_assert('fleet_monthly_histories' in dir(), "Run Cell 0 first")

# Get output directory from PARAMS_FILE (defined in Cell 0)
PARAMS_FILE = require_global("PARAMS_FILE")
OUTPUT_DIR = Path(PARAMS_FILE).parent

# Get visualization parameters
revenue_display_start_year = VIZ_PARAMS['revenue_display_start_year']

n_assets = len(fleet_summaries)
lifespans = np.array([s['lifespan_years'] for s in fleet_summaries])

# Check that revenue data exists - NO FALLBACK
sample_hist = fleet_monthly_histories[0]
print(f"   Available keys in monthly history: {list(sample_hist.keys())}")

hard_assert('monthly_cumulative_revenue_history' in sample_hist,
    "MISSING: 'monthly_cumulative_revenue_history' not in fleet_monthly_histories. "
    "Re-run SAGE_main.ipynb to generate revenue data. "
    "Ensure Cell 9/10 exports monthly_cumulative_revenue_history.")

print("   Using actual simulation revenue data")

# Dynamic display range
display_years = int(np.ceil(lifespans.max())) + 1
display_months = display_years * 12

# Pull actual cumulative revenue with proper NaN handling
cum_revenue_matrix = np.full((n_assets, display_months + 1), np.nan)

for i, hist in enumerate(fleet_monthly_histories):
    hard_assert('monthly_cumulative_revenue_history' in hist,
        f"MISSING: 'monthly_cumulative_revenue_history' not in fleet_monthly_histories[{i}]")

    rev = np.array(hist['monthly_cumulative_revenue_history'], dtype=float) / 1000.0  # Convert to $k

    # Find last valid (non-NaN) value for carry-forward
    valid_mask = np.isfinite(rev)
    if not np.any(valid_mask):
        print(f"   WARNING: Asset {i} has no valid revenue data")
        continue

    last_valid_idx = np.where(valid_mask)[0][-1]
    last_valid_revenue = rev[last_valid_idx]

    # Copy valid data
    valid_len = min(len(rev), display_months + 1)
    cum_revenue_matrix[i, :valid_len] = rev[:valid_len]

    # Carry forward the LAST VALID value (not rev[-1] which may be NaN)
    cum_revenue_matrix[i, last_valid_idx:] = last_valid_revenue

# Validate we have usable data
valid_assets = np.sum(np.any(np.isfinite(cum_revenue_matrix), axis=1))
hard_assert(valid_assets > 0, "No valid revenue data found in any asset")
print(f"   Valid assets: {valid_assets}/{n_assets}")

# Check for all-NaN columns (shouldn't happen after carry-forward)
all_nan_cols = np.all(np.isnan(cum_revenue_matrix), axis=0)
if np.any(all_nan_cols):
    first_bad_col = np.where(all_nan_cols)[0][0]
    print(f"   WARNING: All-NaN column starting at month {first_bad_col}")

# Compute statistics (nanpercentile handles remaining NaNs gracefully)
months_arr = np.arange(cum_revenue_matrix.shape[1])
years = months_arr / 12.0

cum_revenue_10 = np.nanpercentile(cum_revenue_matrix, 10, axis=0)
cum_revenue_25 = np.nanpercentile(cum_revenue_matrix, 25, axis=0)
cum_revenue_50 = np.nanpercentile(cum_revenue_matrix, 50, axis=0)
cum_revenue_75 = np.nanpercentile(cum_revenue_matrix, 75, axis=0)
cum_revenue_90 = np.nanpercentile(cum_revenue_matrix, 90, axis=0)
cum_revenue_mean = np.nanmean(cum_revenue_matrix, axis=0)

# Validate statistics are usable
hard_assert(np.isfinite(cum_revenue_50[-1]),
    f"Median revenue at end is NaN. Check revenue data export in SAGE Cell 9/10.")
hard_assert(np.isfinite(cum_revenue_90[-1]),
    f"90th percentile revenue at end is NaN. Check revenue data export.")

# =============================================================================
# FIGURE 4 FOR JOULE (single panel, clean)
# =============================================================================
fig, ax = plt.subplots(figsize=(7, 5))

# Plot percentile bands ONLY (no individual trajectories)
ax.fill_between(years, cum_revenue_10, cum_revenue_90, alpha=0.25, color='#2ecc71',
                label='10–90th percentile', linewidth=0)
ax.fill_between(years, cum_revenue_25, cum_revenue_75, alpha=0.5, color='#2ecc71',
                label='25–75th percentile', linewidth=0)
ax.plot(years, cum_revenue_50, '--', color='#1a7f43', linewidth=1.5, label='Median')
ax.plot(years, cum_revenue_mean, '-', color='#1a7f43', linewidth=2, label='Mean')

ax.set_xlabel('Time (years)', fontsize=11)
ax.set_ylabel('Cumulative revenue ($k)', fontsize=11)
ax.legend(loc='lower right', fontsize=9, framealpha=0.9)

# Zoom to divergence region - USING PARAM
start_month = revenue_display_start_year * 12
hard_assert(start_month < len(cum_revenue_10),
    f"revenue_display_start_year ({revenue_display_start_year}) exceeds data range ({len(cum_revenue_10)/12:.1f} years)")

# Validate y-limits before setting
y_min_raw = cum_revenue_10[start_month]
y_max_raw = cum_revenue_90[-1]

hard_assert(np.isfinite(y_min_raw),
    f"y_min is NaN at month {start_month}. Revenue data may not extend that far.")
hard_assert(np.isfinite(y_max_raw),
    f"y_max is NaN. Final revenue statistics are invalid.")

ax.set_xlim(revenue_display_start_year, display_years)
y_min = y_min_raw * 0.98
y_max = y_max_raw * 1.03
ax.set_ylim(y_min, y_max)

ax.grid(False)

# Annotation
final_spread = cum_revenue_90[-1] - cum_revenue_10[-1]
pct_spread = 100 * final_spread / cum_revenue_50[-1]
ax.annotate(f'Lifetime gap: ${final_spread:.0f}k ({pct_spread:.0f}%)',
            xy=(display_years - 0.3, cum_revenue_90[-1]),
            fontsize=10, ha='right', va='bottom',
            bbox=dict(boxstyle='round,pad=0.3', facecolor='wheat', alpha=0.8))

plt.tight_layout()
fig.savefig(OUTPUT_DIR / 'figure_4_revenue_divergence.png', dpi=300, bbox_inches='tight')
fig.savefig(OUTPUT_DIR / 'figure_4_revenue_divergence.pdf', bbox_inches='tight')
plt.show()

print(f"\nFigure 4 Summary:")
print(f"   Median lifetime revenue: ${cum_revenue_50[-1]:.0f}k")
print(f"   10-90th percentile gap: ${final_spread:.0f}k ({pct_spread:.0f}%)")
print(f"\nParameters Used:")
print(f"   revenue_display_start_year: {revenue_display_start_year}")
print(f"\nSaved: figure_4_revenue_divergence.png/.pdf to {OUTPUT_DIR}")

# Cell VIZ-4: Fleet Heterogeneity Validation Figure 6 and for Joule
# ------------------------------------------
# Produces:
#   1. Original 6-panel diagnostic figure (viz4_fleet_heterogeneity.png)
#   2. Joule Figure 2: 2-panel fleet distribution + survival (figure_2_fleet_distribution.png/pdf)

import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import weibull_min, pearsonr
from pathlib import Path

print("VIZ-4: Generating fleet heterogeneity plots...")

hard_assert('fleet_summaries' in dir(), "Run Cell 0 first")
hard_assert('fleet_monthly_histories' in dir(), "Run Cell 0 first")
hard_assert(len(fleet_summaries) > 1, "Need multiple assets for fleet analysis")

# Setup output directory
OUTPUT_DIR = require_global("OUTPUT_DIR")

# Get visualization parameters - FIXED: was hard-coded
cohort_high_pct = VIZ_PARAMS['cohort_high_pct']
cohort_low_pct = VIZ_PARAMS['cohort_low_pct']
position_high = VIZ_PARAMS['position_high']
position_low = VIZ_PARAMS['position_low']

n_assets = len(fleet_summaries)
sim_years = int(require_param("simulation_years"))
eol_soh = require_param("SoH_EOL")

# Extract summary data
quality_factors = np.array([s['quality_factor'] for s in fleet_summaries])
gradient_factors = np.array([s['vertical_pos'] for s in fleet_summaries])
lifespans = np.array([s['lifespan_years'] for s in fleet_summaries])
final_soh = np.array([s['final_soh'] for s in fleet_summaries])

# Build monthly arrays
max_months = sim_years * 12
soh_matrix = np.full((n_assets, max_months), np.nan)
for i, hist in enumerate(fleet_monthly_histories):
    soh_arr = np.array(hist['monthly_soh_history'])
    valid_len = min(len(soh_arr), max_months)
    soh_matrix[i, :valid_len] = soh_arr[:valid_len]

# Cohort definitions - USING VIZ_PARAMS
q_high_idx = np.where(quality_factors >= np.percentile(quality_factors, cohort_high_pct))[0]
q_low_idx = np.where(quality_factors <= np.percentile(quality_factors, cohort_low_pct))[0]
pos_top_idx = np.where(gradient_factors >= position_high)[0]
pos_bot_idx = np.where(gradient_factors <= position_low)[0]

# Alive mask for survival curves
alive_mask = np.zeros((n_assets, max_months), dtype=bool)
for i in range(n_assets):
    months_alive = int(np.clip(lifespans[i] * 12, 0, max_months))
    alive_mask[i, :months_alive] = True

# Build temperature matrix
T_matrix = np.full((n_assets, max_months), np.nan)
for i, hist in enumerate(fleet_monthly_histories):
    T_arr = np.array(hist['monthly_T_cell_mean_history'])
    valid_len = min(len(T_arr), max_months)
    T_matrix[i, :valid_len] = T_arr[:valid_len]

mean_T = np.array([np.nanmean(T_matrix[i, :]) for i in range(n_assets)])

# Fit Weibull distribution (used in both figures)
try:
    shape, loc, scale = weibull_min.fit(lifespans, floc=0)
    beta_weibull = shape
    eta_weibull = scale
    weibull_fitted = True
except:
    beta_weibull = np.nan
    eta_weibull = np.nan
    weibull_fitted = False

# =============================================================================
# FIGURE 2 FOR JOULE (2 panels) - Generate first for priority
# =============================================================================
fig2, (ax2a, ax2b) = plt.subplots(1, 2, figsize=(10, 4.5))

# Panel A: Fleet lifespan histogram with Weibull fit
bins = np.linspace(lifespans.min() - 0.5, lifespans.max() + 0.5, 25)
ax2a.hist(lifespans, bins=bins, color='#2ecc71', edgecolor='black',
          alpha=0.7, density=True)

if weibull_fitted:
    xs = np.linspace(lifespans.min() * 0.95, lifespans.max() * 1.05, 200)
    weibull_pdf = weibull_min.pdf(xs, shape, loc=0, scale=scale)
    ax2a.plot(xs, weibull_pdf, 'k-', linewidth=2, label='Weibull fit')

ax2a.axvline(np.median(lifespans), color='#3498db', linestyle='--', linewidth=2,
             label=f'Median: {np.median(lifespans):.1f} yr')

ax2a.set_xlabel('Asset lifespan (years)', fontsize=11)
ax2a.set_ylabel('Probability density', fontsize=11)
ax2a.legend(loc='upper left', fontsize=9, framealpha=0.9)
ax2a.set_xlim(lifespans.min() - 1, lifespans.max() + 1)
ax2a.grid(False)

# Panel B: Aggregate fleet survival curve (NO cohorts)
months = np.arange(max_months)
fleet_survival = np.mean(alive_mask, axis=0)  # Aggregate across ALL assets

ax2b.plot(months / 12.0, fleet_survival, color='#2ecc71', linewidth=2.5)
ax2b.fill_between(months / 12.0, 0, fleet_survival, color='#2ecc71', alpha=0.15)

# Mark median survival time
median_survival_month = np.searchsorted(-fleet_survival, -0.5)
median_survival_year = median_survival_month / 12.0
ax2b.axhline(0.5, color='#3498db', linestyle='--', linewidth=1.5, alpha=0.7)
ax2b.axvline(median_survival_year, color='#3498db', linestyle='--', linewidth=1.5, alpha=0.7)

ax2b.set_xlabel('Time (years)', fontsize=11)
ax2b.set_ylabel('Fraction of fleet operational', fontsize=11)
ax2b.set_xlim(0, sim_years)
ax2b.set_ylim(-0.02, 1.02)
ax2b.grid(False)

fig2.tight_layout()
fig2.savefig(OUTPUT_DIR / 'figure_2_fleet_distribution.png', dpi=300, bbox_inches='tight')
fig2.savefig(OUTPUT_DIR / 'figure_2_fleet_distribution.pdf', bbox_inches='tight')
plt.show()
print(f"Saved: figure_2_fleet_distribution.png/.pdf to {OUTPUT_DIR}")

# =============================================================================
# ORIGINAL 6-PANEL DIAGNOSTIC FIGURE
# =============================================================================
fig, axes = plt.subplots(2, 3, figsize=(16, 10))

# Plot 1: SoH distribution at multiple time points
ax1 = axes[0, 0]
years_to_show = [10, 15, 20]
colors = plt.cm.viridis(np.linspace(0.2, 0.8, len(years_to_show)))
for i, year in enumerate(years_to_show):
    month_idx = year * 12 - 1
    if month_idx < max_months:
        soh_at_year = soh_matrix[:, month_idx]
        soh_valid = soh_at_year[~np.isnan(soh_at_year)]
        if len(soh_valid) > 0:
            ax1.hist(soh_valid, bins=15, alpha=0.5, color=colors[i],
                     label=f'Year {year} (n={len(soh_valid)})')
ax1.set_xlabel('State of Health')
ax1.set_ylabel('Count')
ax1.set_title('Fleet SoH Distribution Over Time')
ax1.legend()
ax1.grid(True, alpha=0.3)

# Plot 2: Survival curves by cohort
ax2 = axes[0, 1]
for idx, label, style in [(q_high_idx, f'High Quality (>{cohort_high_pct}%ile)', '-'),
                           (q_low_idx, f'Low Quality (<{cohort_low_pct}%ile)', '-'),
                           (pos_bot_idx, f'Bottom Rack (<{position_low})', '--'),
                           (pos_top_idx, f'Top Rack (>{position_high})', '--')]:
    if len(idx) > 0:
        survival = np.mean(alive_mask[idx, :], axis=0)
        ax2.plot(months / 12.0, survival, style, linewidth=2, label=label)
ax2.set_xlabel('Years')
ax2.set_ylabel('Fraction Alive')
ax2.set_title('Survival Curves by Cohort')
ax2.legend()
ax2.grid(True, alpha=0.3)
ax2.set_ylim(-0.02, 1.02)

# Plot 3: Lifespan histogram with Weibull fit
ax3 = axes[0, 2]
bins = np.linspace(lifespans.min() - 0.5, lifespans.max() + 0.5, 15)
ax3.hist(lifespans, bins=bins, color='mediumseagreen', edgecolor='black',
         alpha=0.7, density=True)

if weibull_fitted:
    xs = np.linspace(lifespans.min() * 0.9, lifespans.max() * 1.1, 200)
    weibull_pdf = weibull_min.pdf(xs, shape, loc=0, scale=scale)
    ax3.plot(xs, weibull_pdf, 'k-', linewidth=2, label='Weibull fit')

ax3.axvline(np.median(lifespans), color='blue', linestyle='--', linewidth=2,
            label=f'Median: {np.median(lifespans):.1f}y')
ax3.axvline(sim_years, color='red', linestyle=':', linewidth=2,
            label=f'Sim horizon: {sim_years}y')
ax3.set_xlabel('Years to EOL')
ax3.set_ylabel('Probability Density')
ax3.set_title(f'Fleet Lifespan Distribution (Weibull beta={beta_weibull:.1f})')
ax3.legend()
ax3.grid(True, alpha=0.3)

# Plot 4: T_cell by cohort
ax4 = axes[1, 0]
for idx, label, color in [(pos_bot_idx, f'Bottom Rack (<{position_low})', 'blue'),
                           (pos_top_idx, f'Top Rack (>{position_high})', 'red')]:
    if len(idx) > 0:
        T_cohort = T_matrix[idx, :]
        # Avoid warning by checking for valid data
        if np.any(~np.isnan(T_cohort)):
            T_mean = np.nanmean(T_cohort, axis=0)
            ax4.plot(months / 12.0, T_mean, color=color, linewidth=2, label=label)
ax4.set_xlabel('Years')
ax4.set_ylabel('Mean T_cell (C)')
ax4.set_title('Cell Temperature by Rack Position')
ax4.legend()
ax4.grid(True, alpha=0.3)

# Plot 5: Lifespan vs Temperature (colored by quality)
ax5 = axes[1, 1]
q_norm = (quality_factors - quality_factors.min()) / (quality_factors.max() - quality_factors.min())
scatter1 = ax5.scatter(mean_T, lifespans, c=q_norm, cmap='RdYlGn', s=60, alpha=0.7,
                       edgecolor='black', linewidth=0.5)

mask = np.isfinite(mean_T) & np.isfinite(lifespans)
coeffs = np.polyfit(mean_T[mask], lifespans[mask], 1)
r_temp, _ = pearsonr(mean_T[mask], lifespans[mask])
r2_temp = r_temp ** 2

T_range = np.linspace(mean_T.min(), mean_T.max(), 100)
ax5.plot(T_range, np.polyval(coeffs, T_range), 'r-', linewidth=2)

ax5.set_xlabel('Mean Cell Temperature (C)')
ax5.set_ylabel('Lifespan (years)')
ax5.set_title(f'Lifespan vs Temperature (R2 = {r2_temp:.2f})')
cbar1 = plt.colorbar(scatter1, ax=ax5)
cbar1.set_label('Quality Factor')
ax5.grid(True, alpha=0.3)

# Plot 6: Lifespan vs Quality (colored by temperature)
ax6 = axes[1, 2]
T_norm = (mean_T - mean_T.min()) / (mean_T.max() - mean_T.min())
scatter2 = ax6.scatter(quality_factors, lifespans, c=T_norm, cmap='coolwarm', s=60,
                       alpha=0.7, edgecolor='black', linewidth=0.5)

mask = np.isfinite(quality_factors) & np.isfinite(lifespans)
coeffs_q = np.polyfit(quality_factors[mask], lifespans[mask], 1)
r_qual, _ = pearsonr(quality_factors[mask], lifespans[mask])
r2_qual = r_qual ** 2

q_range = np.linspace(quality_factors.min(), quality_factors.max(), 100)
ax6.plot(q_range, np.polyval(coeffs_q, q_range), 'r-', linewidth=2)

ax6.set_xlabel('Quality Factor')
ax6.set_ylabel('Lifespan (years)')
ax6.set_title(f'Lifespan vs Quality (R2 = {r2_qual:.2f})')
cbar2 = plt.colorbar(scatter2, ax=ax6)
cbar2.set_label('Temperature (C)')
ax6.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('viz4_fleet_heterogeneity.png', dpi=150, bbox_inches='tight')
plt.show()

# Print summary
print(f"\nFleet Summary ({n_assets} assets):")
print(f"   Quality factor: mean={quality_factors.mean():.3f}, std={quality_factors.std():.3f}")
print(f"   Vertical position: mean={gradient_factors.mean():.3f}, std={gradient_factors.std():.3f}")
print(f"   Lifespan: mean={lifespans.mean():.1f}y, std={lifespans.std():.1f}y, range=[{lifespans.min():.1f}, {lifespans.max():.1f}]")

if weibull_fitted:
    print(f"\nWeibull Fit:")
    print(f"   Shape (beta): {beta_weibull:.2f}  (beta>1 = wear-out failures)")
    print(f"   Scale (eta): {eta_weibull:.2f} years")

print(f"\nStressor Effects on Lifespan:")
print(f"   Temperature: R2 = {r2_temp:.3f} (r = {r_temp:.3f})")
print(f"   Quality:     R2 = {r2_qual:.3f} (r = {r_qual:.3f})")
print(f"   Combined:    R2 ~ {min(1.0, r2_temp + r2_qual):.3f} (approximate, assumes independence)")

print(f"\nCohort Sizes:")
print(f"   High quality (>{cohort_high_pct}%ile): {len(q_high_idx)} assets")
print(f"   Low quality (<{cohort_low_pct}%ile): {len(q_low_idx)} assets")
print(f"   Top rack (>{position_high}): {len(pos_top_idx)} assets")
print(f"   Bottom rack (<{position_low}): {len(pos_bot_idx)} assets")

print(f"\nParameters Used:")
print(f"   cohort_high_pct: {cohort_high_pct}")
print(f"   cohort_low_pct: {cohort_low_pct}")
print(f"   position_high: {position_high}")
print(f"   position_low: {position_low}")

# Cell VIZ-5: Arrhenius Activation Energy Validation Figure 4
# --------------------------------------------------
# Validates: E_a_cal and E_a_cyc recovery from fleet simulation data
#
# METHODOLOGY:
#   - E_a_cal: Extracted from stress accumulation rate (t_cal_cumulative / elapsed_hours)
#     This directly measures the Arrhenius factor without sqrt(t) confounding
#   - E_a_cyc: Extracted from cycle aging per unit throughput (q_cyc / cumulative_kwh)
#     This isolates the temperature dependence of cycle damage
#
# The capacity loss rate (used in previous versions) gives a BLENDED effective E_a
# that is confounded by sqrt(t) kinetics and calendar/cycle mixing. It should NOT be
# used to validate individual activation energies.

import matplotlib.pyplot as plt
import numpy as np

print("VIZ-5: Generating Arrhenius activation energy validation plots...")

hard_assert('fleet_summaries' in dir(), "Run Cell 0 first")
hard_assert('fleet_monthly_histories' in dir(), "Run Cell 0 first")
hard_assert(len(fleet_summaries) > 10, "Need more assets for Arrhenius analysis")

# Check that new fields exist
hard_assert('final_t_cal_cumulative' in fleet_summaries[0],
            "Run Cell 8C with updated Cell 8B that exports final_t_cal_cumulative")
hard_assert('final_elapsed_hours' in fleet_summaries[0],
            "Run Cell 8C with updated Cell 8B that exports final_elapsed_hours")

n_assets = len(fleet_summaries)
sim_years = int(require_param("simulation_years"))
R_gas = require_param("phys_R_gas")
T_ref_K = require_param("phys_T_ref_kelvin")
E_a_cal_cfg = require_param("E_a_cal")
E_a_cyc_cfg = require_param("E_a_cyc")
cap_nom = require_param("capacity_kwh")

# Extract data from fleet summaries and histories
mean_temps = []
stress_rates = []
cyc_rates_per_kwh = []
final_qcal = []
final_qcyc = []
elapsed_hours_list = []

for i, (summary, hist) in enumerate(zip(fleet_summaries, fleet_monthly_histories)):
    T_hist = np.array(hist['monthly_T_cell_mean_history'])
    valid = ~np.isnan(T_hist)

    if np.sum(valid) < 12:
        continue

    mean_T = np.mean(T_hist[valid])
    t_cal_cum = summary['final_t_cal_cumulative']
    elapsed_hrs = summary['final_elapsed_hours']

    qcal_hist = np.array(hist['monthly_qcal_history'])
    qcyc_hist = np.array(hist['monthly_qcyc_history'])
    qcal_final = qcal_hist[valid][-1] if np.sum(valid) > 0 else np.nan
    qcyc_final = qcyc_hist[valid][-1] if np.sum(valid) > 0 else np.nan

    cumulative_kwh = summary.get('cycles', 0) * cap_nom

    if elapsed_hrs > 0 and t_cal_cum > 0 and cumulative_kwh > 0:
        mean_temps.append(mean_T)
        stress_rates.append(t_cal_cum / elapsed_hrs)
        cyc_rates_per_kwh.append(qcyc_final / cumulative_kwh if cumulative_kwh > 0 else np.nan)
        final_qcal.append(qcal_final)
        final_qcyc.append(qcyc_final)
        elapsed_hours_list.append(elapsed_hrs)

mean_temps = np.array(mean_temps)
stress_rates = np.array(stress_rates)
cyc_rates_per_kwh = np.array(cyc_rates_per_kwh)
final_qcal = np.array(final_qcal)
final_qcyc = np.array(final_qcyc)
elapsed_hours = np.array(elapsed_hours_list)

T_kelvin = mean_temps + 273.15
inv_T_1000 = 1000.0 / T_kelvin

fig, axes = plt.subplots(2, 2, figsize=(13, 10))

# -------------------------------------------------------------------------
# Plot 1: E_a_cal validation - Stress accumulation rate vs 1/T
# -------------------------------------------------------------------------
ax1 = axes[0, 0]
ln_stress_rate = np.log(stress_rates)
ax1.scatter(inv_T_1000, ln_stress_rate, alpha=0.6, s=40, color='darkorange', edgecolor='black', linewidth=0.5)
ax1.set_xlabel('1000/T (1/K)')
ax1.set_ylabel('ln(Stress Accumulation Rate)')
ax1.set_title('Calendar Aging: E_a_cal Validation')
ax1.grid(True, alpha=0.3)

z_cal = np.polyfit(inv_T_1000, ln_stress_rate, 1)
x_fit = np.linspace(inv_T_1000.min(), inv_T_1000.max(), 100)
ax1.plot(x_fit, np.polyval(z_cal, x_fit), 'r-', linewidth=2)

E_a_cal_extracted = -z_cal[0] * R_gas * 1000
ax1.text(0.05, 0.95, f'Extracted E_a_cal = {E_a_cal_extracted/1000:.1f} kJ/mol\nConfigured: {E_a_cal_cfg/1000:.1f} kJ/mol',
         transform=ax1.transAxes, fontsize=10, verticalalignment='top',
         bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.8))

# -------------------------------------------------------------------------
# Plot 2: E_a_cyc validation - Cycle aging per kWh vs 1/T
# -------------------------------------------------------------------------
ax2 = axes[0, 1]
valid_cyc = np.isfinite(cyc_rates_per_kwh) & (cyc_rates_per_kwh > 0)
if np.sum(valid_cyc) > 10:
    ln_cyc_rate = np.log(cyc_rates_per_kwh[valid_cyc])
    inv_T_cyc = inv_T_1000[valid_cyc]
    ax2.scatter(inv_T_cyc, ln_cyc_rate, alpha=0.6, s=40, color='forestgreen', edgecolor='black', linewidth=0.5)

    z_cyc = np.polyfit(inv_T_cyc, ln_cyc_rate, 1)
    x_fit_cyc = np.linspace(inv_T_cyc.min(), inv_T_cyc.max(), 100)
    ax2.plot(x_fit_cyc, np.polyval(z_cyc, x_fit_cyc), 'r-', linewidth=2)

    E_a_cyc_extracted = -z_cyc[0] * R_gas * 1000
    ax2.text(0.05, 0.95, f'Extracted E_a_cyc = {E_a_cyc_extracted/1000:.1f} kJ/mol\nConfigured: {E_a_cyc_cfg/1000:.1f} kJ/mol',
             transform=ax2.transAxes, fontsize=10, verticalalignment='top',
             bbox=dict(boxstyle='round', facecolor='lightgreen', alpha=0.8))
else:
    E_a_cyc_extracted = np.nan
    ax2.text(0.5, 0.5, 'Insufficient valid cycle data', ha='center', va='center', transform=ax2.transAxes)

ax2.set_xlabel('1000/T (1/K)')
ax2.set_ylabel('ln(Cycle Aging Rate per kWh)')
ax2.set_title('Cycle Aging: E_a_cyc Validation')
ax2.grid(True, alpha=0.3)

# -------------------------------------------------------------------------
# Plot 3: Stress rate vs Temperature (linear scale, intuitive view)
# -------------------------------------------------------------------------
ax3 = axes[1, 0]
ax3.scatter(mean_temps, stress_rates, alpha=0.6, s=40, color='darkorange', edgecolor='black', linewidth=0.5)
ax3.set_xlabel('Mean Cell Temperature (C)')
ax3.set_ylabel('Stress Accumulation Rate (t_eff/t_elapsed)')
ax3.set_title('Calendar Stress Rate vs Temperature')
ax3.grid(True, alpha=0.3)

theoretical_stress = np.exp((E_a_cal_cfg / R_gas) * (1.0 / T_ref_K - 1.0 / T_kelvin))
sort_idx = np.argsort(mean_temps)
ax3.plot(mean_temps[sort_idx], theoretical_stress[sort_idx], 'b--', linewidth=2,
         label=f'Theoretical (E_a={E_a_cal_cfg/1000:.0f} kJ/mol)')
ax3.legend()

# -------------------------------------------------------------------------
# Plot 4: Validation summary - Extracted vs Configured
# -------------------------------------------------------------------------
ax4 = axes[1, 1]

labels = ['E_a_cal\n(Calendar)', 'E_a_cyc\n(Cycle)']
configured = [E_a_cal_cfg / 1000, E_a_cyc_cfg / 1000]
extracted = [E_a_cal_extracted / 1000, E_a_cyc_extracted / 1000 if np.isfinite(E_a_cyc_extracted) else 0]

x_pos = np.arange(len(labels))
width = 0.35

bars1 = ax4.bar(x_pos - width/2, configured, width, label='Configured (Input)', color='steelblue', edgecolor='black')
bars2 = ax4.bar(x_pos + width/2, extracted, width, label='Extracted (Output)', color='coral', edgecolor='black')

ax4.set_ylabel('Activation Energy (kJ/mol)')
ax4.set_title('Arrhenius Validation: Input vs Output')
ax4.set_xticks(x_pos)
ax4.set_xticklabels(labels)
ax4.legend()
ax4.grid(True, alpha=0.3, axis='y')

for bar, val in zip(bars1, configured):
    ax4.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1, f'{val:.1f}',
             ha='center', va='bottom', fontsize=10, fontweight='bold')
for bar, val in zip(bars2, extracted):
    if val > 0:
        ax4.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1, f'{val:.1f}',
                 ha='center', va='bottom', fontsize=10, fontweight='bold')

ax4.set_ylim(0, max(configured + extracted) * 1.2)

plt.tight_layout()
plt.savefig('viz5_arrhenius_validation.png', dpi=150, bbox_inches='tight')
plt.show()

# -------------------------------------------------------------------------
# Print validation summary
# -------------------------------------------------------------------------
print(f"\n{'='*60}")
print(f"ARRHENIUS ACTIVATION ENERGY VALIDATION")
print(f"{'='*60}")
print(f"\nTemperature range: {mean_temps.min():.1f}C to {mean_temps.max():.1f}C")
print(f"Assets analyzed: {len(mean_temps)}")

print(f"\nCALENDAR AGING (E_a_cal):")
print(f"   Configured:  {E_a_cal_cfg/1000:.1f} kJ/mol")
print(f"   Extracted:   {E_a_cal_extracted/1000:.1f} kJ/mol")
pct_error_cal = 100 * (E_a_cal_extracted - E_a_cal_cfg) / E_a_cal_cfg
print(f"   Error:       {pct_error_cal:+.1f}%")
if abs(pct_error_cal) < 10:
    print(f"   Status:      VALIDATED (within 10%)")
else:
    print(f"   Status:      DISCREPANCY (>10% error)")

print(f"\nCYCLE AGING (E_a_cyc):")
print(f"   Configured:  {E_a_cyc_cfg/1000:.1f} kJ/mol")
if np.isfinite(E_a_cyc_extracted):
    print(f"   Extracted:   {E_a_cyc_extracted/1000:.1f} kJ/mol")
    pct_error_cyc = 100 * (E_a_cyc_extracted - E_a_cyc_cfg) / E_a_cyc_cfg
    print(f"   Error:       {pct_error_cyc:+.1f}%")
    if abs(pct_error_cyc) < 15:
        print(f"   Status:      VALIDATED (within 15%)")
    else:
        print(f"   Status:      DISCREPANCY (>15% error)")
else:
    print(f"   Extracted:   Unable to compute (insufficient data)")

print(f"\n{'='*60}")

# Cell VIZ-6: SOC and Energy Validation Figure S1
# -------------------------------------
# Validates: Daily cycling pattern, SOC window contraction, usable energy

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

print("VIZ-6: Generating SOC and energy plots...")

hard_assert(last_asset_traj_year1 is not None, "Run Cell 0 first")
hard_assert(last_asset_env_year1 is not None, "Run Cell 0 first")

n = len(last_asset_traj_year1)
soc = np.array([state['soc_true'] for state in last_asset_traj_year1])
soh = np.array([state['soh_true'] for state in last_asset_traj_year1])
timestamps = [env['t_timestamp'] for env in last_asset_env_year1[:n]]

soc_min_bol = require_param("SoC_min_BOL")
soc_max_bol = require_param("SoC_max_BOL")
soc_min_eol = require_param("SoC_min_EOL")
soc_max_eol = require_param("SoC_max_EOL")
soh_eol = require_param("SoH_EOL")
cap_nom = require_param("capacity_kwh")

fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# Plot 1: SOC trajectory (first week)
ax1 = axes[0, 0]
week_hours = min(168, n)
hours = np.arange(week_hours)
ax1.plot(hours, soc[:week_hours], 'b-', linewidth=1.5)
ax1.axhline(y=soc_max_bol, color='g', linestyle='--', alpha=0.7, label='SOC Max (BOL)')
ax1.axhline(y=soc_min_bol, color='r', linestyle='--', alpha=0.7, label='SOC Min (BOL)')
ax1.set_xlabel('Hour')
ax1.set_ylabel('State of Charge')
ax1.set_title('SOC Profile (First Week)')
ax1.legend()
ax1.grid(True, alpha=0.3)
ax1.set_ylim([0, 1.05])
for d in range(8):
    ax1.axvline(x=d*24, color='gray', linestyle=':', alpha=0.5)

# Plot 2: SOC daily pattern (averaged)
ax2 = axes[0, 1]
df_soc = pd.DataFrame({'timestamp': timestamps, 'soc': soc})
df_soc['hour'] = pd.to_datetime(df_soc['timestamp']).dt.hour
hourly_soc = df_soc.groupby('hour')['soc'].agg(['mean', 'std'])

# Clip confidence bands to physical SOC limits [soc_min_bol, soc_max_bol]
soc_upper_band = np.clip(hourly_soc['mean'] + hourly_soc['std'], soc_min_bol, soc_max_bol)
soc_lower_band = np.clip(hourly_soc['mean'] - hourly_soc['std'], soc_min_bol, soc_max_bol)

ax2.fill_between(hourly_soc.index,
                  soc_lower_band,
                  soc_upper_band,
                  alpha=0.3)
ax2.plot(hourly_soc.index, hourly_soc['mean'], 'b-', linewidth=2)
ax2.axhline(y=soc_max_bol, color='g', linestyle='--', alpha=0.5, label='SOC Max (BOL)')
ax2.axhline(y=soc_min_bol, color='r', linestyle='--', alpha=0.5, label='SOC Min (BOL)')
ax2.set_xlabel('Hour of Day')
ax2.set_ylabel('State of Charge')
ax2.set_title('Average Daily SOC Pattern (+/-1 std, clipped to BOL limits)')
ax2.set_ylim([0, 1.0])
ax2.legend(loc='lower left')
ax2.grid(True, alpha=0.3)
ax2.set_xticks(range(0, 24, 3))

# Plot 3: SOC window vs SoH
ax3 = axes[1, 0]
soh_range = np.linspace(soh_eol, 1.0, 50)
deg_progress = (1.0 - soh_range) / (1.0 - soh_eol)
soc_max_degraded = soc_max_bol - (soc_max_bol - soc_max_eol) * deg_progress
soc_min_degraded = soc_min_bol + (soc_min_eol - soc_min_bol) * deg_progress
ax3.fill_between(soh_range, soc_min_degraded, soc_max_degraded, alpha=0.3, label='Usable Window')
ax3.plot(soh_range, soc_max_degraded, 'g-', linewidth=2, label='SOC Max')
ax3.plot(soh_range, soc_min_degraded, 'r-', linewidth=2, label='SOC Min')
ax3.set_xlabel('State of Health')
ax3.set_ylabel('State of Charge')
ax3.set_title('SOC Window Contraction with Degradation')
ax3.legend()
ax3.grid(True, alpha=0.3)
ax3.set_xlim([soh_eol, 1.0])
ax3.invert_xaxis()

# Plot 4: Usable energy vs SoH
ax4 = axes[1, 1]
window_size = soc_max_degraded - soc_min_degraded
usable_energy = cap_nom * soh_range * window_size
usable_energy_bol = cap_nom * (soc_max_bol - soc_min_bol)
ax4.plot(soh_range, usable_energy, 'b-', linewidth=2, label='Usable Energy')
ax4.axhline(y=usable_energy_bol, color='g', linestyle='--',
            label=f'BOL Usable: {usable_energy_bol:.0f} kWh')
ax4.set_xlabel('State of Health')
ax4.set_ylabel('Usable Energy (kWh)')
ax4.set_title('Usable Energy vs Degradation')
ax4.legend()
ax4.grid(True, alpha=0.3)
ax4.set_xlim([soh_eol, 1.0])
ax4.invert_xaxis()

plt.tight_layout()
plt.savefig('viz6_soc_energy.png', dpi=150, bbox_inches='tight')
plt.show()

print(f"\nSOC and Energy Summary:")
print(f"   BOL window: [{soc_min_bol:.2f}, {soc_max_bol:.2f}] = {soc_max_bol-soc_min_bol:.2f}")
print(f"   EOL window: [{soc_min_eol:.2f}, {soc_max_eol:.2f}] = {soc_max_eol-soc_min_eol:.2f}")
print(f"   BOL usable energy: {usable_energy_bol:.0f} kWh")
print(f"   EOL usable energy: {usable_energy[-1]:.0f} kWh")
print(f"   Year-1 SOC range: [{soc.min():.3f}, {soc.max():.3f}]")

# Cell VIZ-7: Environment Generator Validation Figure 1
# --------------------------------------------
# Validates: Price calibration, fat-tail behavior, forecast accuracy
# Uses FULL env_ref (20 years) for stable monthly statistics

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print("VIZ-7: Generating environment validation plots...")

# Use env_ref (full 25 years) if available, otherwise fall back to year-1
if env_ref is not None:
    env_data = env_ref
    data_label = f"{len(env_data):,} hours ({len(env_data)/8760:.1f} years)"
else:
    env_data = last_asset_env_year1
    data_label = f"{len(env_data):,} hours (year 1 only)"
    print("   WARNING: env_ref not available, using year-1 data only")

# Build environment DataFrame
env_df = pd.DataFrame({
    "t_timestamp": [e['t_timestamp'] for e in env_data],
    "p_market": [e['p_market'] for e in env_data],
    "p_forecast": [e['p_forecast'] for e in env_data],
    "T_ambient": [e['T_ambient'] for e in env_data],
})
env_df["t_timestamp"] = pd.to_datetime(env_df["t_timestamp"])
env_df["Month"] = env_df["t_timestamp"].dt.month
env_df["MonthName"] = env_df["t_timestamp"].dt.month_name().str.slice(0, 3)

print(f"   Using {data_label} for validation")

# Load targets - NO DEFAULTS, MUST EXIST IN CSV
target_mean = np.array(require_param("price_mean_monthly"))
pareto_shape_input = require_param("pareto_shape")
price_ceiling = require_param("price_ceiling")

# Get visualization parameters
spike_threshold_multiplier = VIZ_PARAMS['spike_threshold_multiplier']
hill_k_min = VIZ_PARAMS['hill_k_min']
hill_k_max = VIZ_PARAMS['hill_k_max']
hill_k_step = VIZ_PARAMS['hill_k_step']

# Monthly stats
monthly = env_df.groupby("Month", as_index=False).agg(
    Mean_Price=("p_market", "mean"),
    Std_Price=("p_market", "std"),
    MonthName=("MonthName", "first"),
    Count=("p_market", "count"),
)
monthly["Mean_Target"] = target_mean

# Hill estimator for fat tails
def hill_estimator(data, k):
    sorted_data = np.sort(data)[::-1]
    if k >= len(sorted_data) or k < 2:
        return np.nan
    top_k = sorted_data[:k]
    threshold = sorted_data[k]
    if threshold <= 0:
        return np.nan
    log_ratios = np.log(top_k / threshold)
    return k / np.sum(log_ratios)

# -------------------------------------------------------------------------
# SPIKE ISOLATION
# -------------------------------------------------------------------------
prices = env_df["p_market"].values
months = env_df["Month"].values

monthly_means = monthly.set_index("Month")["Mean_Price"].to_dict()

spike_mask = np.zeros(len(prices), dtype=bool)

for m in range(1, 13):
    month_mask = (months == m)
    threshold = monthly_means[m] * spike_threshold_multiplier
    spike_mask |= (month_mask & (prices > threshold))

spike_prices = prices[spike_mask]
n_spikes = len(spike_prices)

print(f"   Spike threshold: {spike_threshold_multiplier}x monthly mean")
print(f"   Spikes detected: {n_spikes}")

n_at_ceiling = int(np.sum(prices >= price_ceiling - 1.0)) if np.isfinite(price_ceiling) else 0

# Normalized prices for deviation distribution
normalized = np.zeros_like(prices)
for m in range(1, 13):
    mask = (months == m)
    if np.sum(mask) > 0:
        mu = np.mean(prices[mask])
        sigma = np.std(prices[mask])
        if sigma > 0:
            normalized[mask] = (prices[mask] - mu) / sigma

# Hill estimates
if n_spikes > 30:
    k_max_actual = min(hill_k_max, n_spikes - 10)
    k_range = np.arange(hill_k_min, k_max_actual, hill_k_step)
    alpha_vs_k = [hill_estimator(spike_prices, k) for k in k_range]
    alpha_effective = np.nanmean(alpha_vs_k) if len(alpha_vs_k) > 0 else np.nan
else:
    k_range = np.array([])
    alpha_vs_k = []
    alpha_effective = np.nan
    print(f"   WARNING: Only {n_spikes} spikes detected (need >30 for Hill estimator)")

# Create figure: 2 calibration plots on top, 3 fat-tail plots on bottom
fig = plt.figure(figsize=(15, 10))

# Row 1: Calibration (2 plots centered)
ax1 = fig.add_subplot(2, 3, 1)
ax2 = fig.add_subplot(2, 3, 3)

# Row 2: Fat-tail analysis (3 plots)
ax3 = fig.add_subplot(2, 3, 4)
ax4 = fig.add_subplot(2, 3, 5)
ax5 = fig.add_subplot(2, 3, 6)

# Plot 1: Monthly Mean Price Calibration
ax1.plot(np.arange(1, 13), monthly["Mean_Price"], "o-", label="Simulated")
ax1.plot(np.arange(1, 13), monthly["Mean_Target"], "s--", label="Target")
ax1.set_xticks(np.arange(1, 13))
ax1.set_xticklabels(monthly["MonthName"].tolist())
ax1.set_ylabel("Mean Price ($/MWh)")
ax1.set_title("Monthly Mean Price Calibration")
ax1.legend()
ax1.grid(True, alpha=0.3)

# Plot 2: Forecast Error Distribution
forecast_error = env_df["p_forecast"] - env_df["p_market"]
ax2.hist(forecast_error, bins=50, density=True, alpha=0.7, edgecolor='black')
ax2.axvline(0, color='red', linestyle='--', linewidth=2)
ax2.set_yscale('log')
ax2.set_xlabel("Forecast Error ($/MWh)")
ax2.set_ylabel("Density (log scale)")
ax2.set_title(f"Forecast Error Distribution (std={forecast_error.std():.2f})")
ax2.grid(True, alpha=0.3)

# Plot 3: Price Deviation Distribution
ax3.hist(normalized, bins=50, density=True, alpha=0.7, edgecolor='black')
ax3.set_yscale('log')
ax3.set_xlabel("Normalized Price Deviation (std)")
ax3.set_ylabel("Density (log scale)")
ax3.set_title("Price Deviation Distribution")
ax3.grid(True, alpha=0.3)

# Plot 4: Log-Log CCDF
if n_spikes > 10:
    sorted_spikes = np.sort(spike_prices)[::-1]
    ccdf = np.arange(1, len(sorted_spikes) + 1) / len(sorted_spikes)
    ax4.loglog(sorted_spikes, ccdf, ".", markersize=3, label=f"Spike prices (n={n_spikes})")
    if np.isfinite(alpha_effective) and alpha_effective > 0:
        x_min = sorted_spikes[-1]
        x_max = sorted_spikes[0]
        x_ref = np.logspace(np.log10(x_min), np.log10(x_max), 100)
        x_anchor = np.median(sorted_spikes)
        y_anchor = np.sum(sorted_spikes >= x_anchor) / len(sorted_spikes)
        y_ref = y_anchor * (x_ref / x_anchor) ** (-alpha_effective)
        ax4.loglog(x_ref, y_ref, "r--", linewidth=2, label=f"Fit alpha_eff={alpha_effective:.2f}")
    ax4.legend()
ax4.set_xlabel("Spike Price ($/MWh)")
ax4.set_ylabel("P(X > x)")
ax4.set_title(f"Log-Log CCDF (Spikes > {spike_threshold_multiplier:.0f}x monthly mean)")
ax4.grid(True, alpha=0.3)

# Plot 5: Hill Plot
if len(k_range) > 0:
    ax5.plot(k_range, alpha_vs_k, ".-", label=f"Effective alpha = {alpha_effective:.2f}")
if np.isfinite(pareto_shape_input):
    ax5.axhline(pareto_shape_input, color="green", linestyle=":", linewidth=2,
                label=f"Pareto input alpha={pareto_shape_input:.1f}")
ax5.set_xlabel("k (number of tail samples)")
ax5.set_ylabel("Estimated alpha")
ax5.set_title("Hill Plot (Effective Tail Index)")
ax5.legend()
ax5.grid(True, alpha=0.3)
ax5.set_ylim(0, 5)

if np.isfinite(alpha_effective) and np.isfinite(pareto_shape_input) and len(k_range) > 0:
    ax5.annotate(
        f"Gap due to lognormal mixing\n& ${price_ceiling:.0f} ceiling",
        xy=(k_range[-1] * 0.6, (alpha_effective + pareto_shape_input) / 2),
        fontsize=9, ha='center', style='italic', color='gray'
    )

plt.tight_layout()
plt.savefig('viz7_environment_validation.png', dpi=150, bbox_inches='tight')
plt.show()

# Summary
print(f"\nEnvironment Validation Summary:")
print(f"   Data: {data_label}")
print(f"   Hours per month: {monthly['Count'].min():,} - {monthly['Count'].max():,}")
print(f"   Price calibration:")
mean_gap = np.abs(monthly["Mean_Price"] - monthly["Mean_Target"]).mean()
print(f"      Mean price MAE: ${mean_gap:.2f}/MWh")
print(f"   Fat-tail analysis (prices > {spike_threshold_multiplier:.0f}x monthly mean):")
print(f"      Number of extreme price events: {n_spikes}")
print(f"      Prices at ceiling (${price_ceiling:.0f}): {n_at_ceiling}")
print(f"   Tail index:")
print(f"      Pareto input: {pareto_shape_input:.2f}")
print(f"      Effective (Hill): {alpha_effective:.2f}")

# Cell VIZ-8: Sensitivity Analysis
# --------------------------------
# Validates: Position and quality effects on lifespan, residualized effects
#
# METHODOLOGY:
#   Uses multivariate regression to isolate independent effects:
#   Lifespan = beta_0 + beta_1(Position) + beta_2(Quality) + epsilon
#   This ensures consistent effect estimates across all four plots.

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print("VIZ-8: Generating sensitivity analysis plots...")

hard_assert('fleet_summaries' in dir(), "Run Cell 0 first")
hard_assert('fleet_monthly_histories' in dir(), "Run Cell 0 first")

sim_years = int(require_param("simulation_years"))
eol_soh = require_param("SoH_EOL")
beta_cal = require_param("beta_cal")
grad_C = require_param("vertical_temp_gradient_C")

deg_budget = 1.0 - eol_soh

# Get visualization parameter - FIXED: was hard-coded 40.0
lifespan_cap = VIZ_PARAMS['lifespan_cap']

df = pd.DataFrame(fleet_summaries)

# Calculate projected life
def calc_projected_life(row):
    t_elapsed = row.get("years_survived", row.get("lifespan_years", sim_years))
    deg_consumed = 1.0 - row["final_soh"]
    if deg_consumed <= 0.001:
        return lifespan_cap
    ratio = deg_budget / deg_consumed
    return min(lifespan_cap, t_elapsed * (ratio ** (1.0 / beta_cal)))

df["Projected_Life"] = df.apply(calc_projected_life, axis=1)

# Mean temperature (last 12 months) - uses helper from Cell 0
df["mean_T_last12"] = [mean_last_n_valid(h['monthly_T_cell_mean_history'], 12)
                        for h in fleet_monthly_histories]

# -------------------------------------------------------------------------
# MULTIVARIATE REGRESSION: Isolate independent effects
# Lifespan = beta_0 + beta_1(Position) + beta_2(Quality) + epsilon
# -------------------------------------------------------------------------
xP = df["vertical_pos"].values.astype(float)
xQ = df["quality_factor"].values.astype(float)
yL = df["Projected_Life"].values.astype(float)

mask = np.isfinite(xP) & np.isfinite(xQ) & np.isfinite(yL)
n_valid = np.sum(mask)

if n_valid >= 4:
    X = np.column_stack([np.ones(n_valid), xP[mask], xQ[mask]])
    coef, residuals, rank, s = np.linalg.lstsq(X, yL[mask], rcond=None)
    beta_0 = float(coef[0])  # Intercept
    beta_pos = float(coef[1])  # Position effect (yr per unit position)
    beta_qual = float(coef[2])  # Quality effect (yr per unit quality)

    # Compute residuals for Plot 3
    yL_predicted = beta_0 + beta_pos * xP + beta_qual * xQ
    residuals_full = yL - yL_predicted
else:
    raise ValueError(f"CRITICAL: Insufficient valid data for regression (n={n_valid})")

# Compute effect magnitudes for Plot 4
# Position effect: full range (0 to 1)
position_range = 1.0
position_effect = beta_pos * position_range

# Quality effect: use actual range in fleet
quality_low = df["quality_factor"].min()
quality_high = df["quality_factor"].max()
quality_range = quality_high - quality_low
quality_effect = beta_qual * quality_range

fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# Plot 1: Position vs Lifespan (with multivariate slope)
ax1 = axes[0, 0]
sc1 = ax1.scatter(df["vertical_pos"], df["Projected_Life"], c=df["quality_factor"],
                  cmap="viridis", s=50, alpha=0.8, edgecolors="k")
# Regression line at mean quality
mean_qual = df["quality_factor"].mean()
x_line = np.array([0, 1])
y_line = beta_0 + beta_pos * x_line + beta_qual * mean_qual
ax1.plot(x_line, y_line, "r--", linewidth=2, label=f"Slope: {beta_pos:.2f} yr/unit (controlled)")
ax1.set_xlabel("Vertical Position (0=bottom, 1=top)")
ax1.set_ylabel("Projected Lifespan (years)")
ax1.set_title(f"Position vs Lifespan (gradient={grad_C}C)")
ax1.legend()
ax1.grid(True, alpha=0.3)
plt.colorbar(sc1, ax=ax1, label="Quality Factor")

# Plot 2: Quality vs Lifespan (with multivariate slope)
ax2 = axes[0, 1]
sc2 = ax2.scatter(df["quality_factor"], df["Projected_Life"], c=df["vertical_pos"],
                  cmap="coolwarm", s=50, alpha=0.8, edgecolors="k")
# Regression line at mean position
mean_pos = df["vertical_pos"].mean()
x_fit = np.array([df["quality_factor"].min(), df["quality_factor"].max()])
y_fit = beta_0 + beta_pos * mean_pos + beta_qual * x_fit
ax2.plot(x_fit, y_fit, "g--", linewidth=2, label=f"Slope: {beta_qual:.2f} yr/unit (controlled)")
ax2.set_xlabel("Quality Factor (<1=worse, >1=better)")
ax2.set_ylabel("Projected Lifespan (years)")
ax2.set_title("Quality vs Lifespan")
ax2.legend()
ax2.grid(True, alpha=0.3)
plt.colorbar(sc2, ax=ax2, label="Vertical Pos (red=top)")

# Plot 3: Residuals vs Quality (after removing both effects)
ax3 = axes[1, 0]
ax3.scatter(xQ[mask], residuals_full[mask], s=30, alpha=0.7)
ax3.axhline(0, color="gray", linewidth=1)
ax3.set_xlabel("Quality Factor")
ax3.set_ylabel("Lifespan Residual (years)")
ax3.set_title("Residuals After Multivariate Regression")
ax3.grid(True, alpha=0.3)

# Compute residual correlation (should be ~0 if model is correct)
resid_corr = float(np.corrcoef(xQ[mask], residuals_full[mask])[0, 1])

# Plot 4: Effect decomposition bar chart (using regression coefficients)
ax4 = axes[1, 1]

effects = {
    "Position\n(top vs bottom)": position_effect,
    "Quality\n(high vs low)": quality_effect,
}
names = list(effects.keys())
values = list(effects.values())
colors = ['red' if v < 0 else 'green' for v in values]
ax4.bar(names, values, color=colors, alpha=0.7, edgecolor='black')
ax4.axhline(0, color='black', linewidth=1)
ax4.set_ylabel("Lifespan Difference (years)")
ax4.set_title("Heterogeneity Effect Magnitudes (from regression)")
ax4.grid(True, alpha=0.3)

for i, v in enumerate(values):
    ax4.text(i, v + 0.1 * np.sign(v), f"{v:+.1f}y", ha='center', fontsize=11)

plt.tight_layout()
plt.savefig('viz8_sensitivity_analysis.png', dpi=150, bbox_inches='tight')
plt.show()

# Summary
print(f"\nSensitivity Analysis Summary (Multivariate Regression):")
print(f"   Model: Lifespan = {beta_0:.2f} + {beta_pos:.2f}*Position + {beta_qual:.2f}*Quality")
print(f"   Position effect (0->1): {position_effect:+.2f} years")
print(f"   Quality effect ({quality_low:.2f}->{quality_high:.2f}): {quality_effect:+.2f} years")
print(f"   Residual-Quality correlation: r = {resid_corr:.4f} (should be ~0)")
print(f"   Interpretation:")
print(f"      - Top-of-rack modules lose {abs(position_effect):.1f} years vs bottom")
print(f"      - High-quality modules gain {abs(quality_effect):.1f} years vs low-quality")
print(f"\nParameters Used:")
print(f"   lifespan_cap: {lifespan_cap}")