# -*- coding: utf-8 -*-
"""sage_strawman.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h6wrrrPcHQS4vtefMH-MM4e2YRyjhlGo
"""

# Cell 0: Mount Google Drive and Load Parameters

import ast
import pandas as pd
from pathlib import Path

DATA_DIR = Path("/content/drive/MyDrive/SAGE/")

# -------------------------------------------------------------------------
# Load parameters from CSV - FAIL FAST
# -------------------------------------------------------------------------
params_path = DATA_DIR / "sage_params.csv"

if not params_path.exists():
    raise FileNotFoundError(f"CRITICAL: {params_path} not found. Cannot proceed.")

params_df = pd.read_csv(params_path)
params = {}
for _, row in params_df.iterrows():
    name = row["name"]
    dtype = str(row["dtype"]).strip()
    if dtype == "float":
        params[name] = float(row["value_float"])
    elif dtype == "int":
        params[name] = int(row["value_float"])
    elif dtype == "bool":
        params[name] = str(row["value_bool"]).strip().upper() == "TRUE"
    elif dtype == "list":
        try:
            params[name] = ast.literal_eval(row["value_list"])
        except:
            raise ValueError(f"Failed to parse list parameter '{name}': {row['value_list']}")

print(f"Loaded {len(params)} parameters from {params_path.name}")


def require_param(key):
    """Get parameter value. Fails immediately if missing."""
    if key not in params:
        raise KeyError(f"MISSING PARAMETER: '{key}' not found in sage_params.csv")
    return params[key]


# -------------------------------------------------------------------------
# Verify required files exist
# -------------------------------------------------------------------------
files_needed = [
    "sage_single_asset_trajectory.csv",
    "sage_fleet_lifespans.csv"
]

print("\nChecking for required files...")
for f in files_needed:
    path = DATA_DIR / f
    if path.exists():
        print(f"  OK: {f}")
    else:
        raise FileNotFoundError(f"MISSING: {f}")

print("\nReady for analysis.")

# Cell 1: Load and diagnose SAGE output
import pandas as pd
import numpy as np
from pathlib import Path

DATA_DIR = Path("/content/drive/MyDrive/SAGE/")

# Load parameters - NO HARDCODING
E_CAP = require_param("capacity_kwh")

# Load SAGE data files
single_asset_path = DATA_DIR / "sage_single_asset_trajectory.csv"
fleet_path = DATA_DIR / "sage_fleet_lifespans.csv"

if not single_asset_path.exists():
    raise FileNotFoundError(f"Single-asset file not found: {single_asset_path}")
if not fleet_path.exists():
    raise FileNotFoundError(f"Fleet file not found: {fleet_path}")

df_single = pd.read_csv(single_asset_path)
df_fleet = pd.read_csv(fleet_path)

print("=" * 70)
print("SINGLE-ASSET SUMMARY")
print("=" * 70)

last = df_single.iloc[-1]
total_loss = last['q_loss_cal'] + last['q_loss_cyc']

print(f"\n  EOL time: {last['years']:.2f} years ({len(df_single)} months)")
print(f"  Final SoH: {last['SoH_SAGE_Truth']:.4f}")
print(f"  q_cal: {last['q_loss_cal']:.4f} ({last['q_loss_cal']/total_loss*100:.1f}% of total loss)")
print(f"  q_cyc: {last['q_loss_cyc']:.4f} ({last['q_loss_cyc']/total_loss*100:.1f}% of total loss)")
print(f"  q_cal/q_cyc ratio: {last['q_loss_cal']/last['q_loss_cyc']:.2f}")
print(f"  Cumulative throughput: {last['cumulative_kwh']:,.0f} kWh")

print("\n" + "=" * 70)
print("FLEET SUMMARY")
print("=" * 70)

print(f"\n  Number of assets: {len(df_fleet)}")
print(f"  Mean lifespan: {df_fleet['lifespan_years'].mean():.2f} years")
print(f"  Std lifespan: {df_fleet['lifespan_years'].std():.2f} years")
print(f"  Min lifespan: {df_fleet['lifespan_years'].min():.2f} years")
print(f"  Max lifespan: {df_fleet['lifespan_years'].max():.2f} years")
print(f"  Range: {df_fleet['lifespan_years'].max() - df_fleet['lifespan_years'].min():.2f} years")

print("\n" + "=" * 70)
print("THROUGHPUT ACCUMULATION CHECK")
print("=" * 70)

years = df_single['years'].values
kwh = df_single['cumulative_kwh'].values

# Linear fit
slope, intercept = np.polyfit(years, kwh, 1)
predicted = slope * years + intercept
residuals = kwh - predicted

# R2 for linearity
ss_res = np.sum(residuals**2)
ss_tot = np.sum((kwh - np.mean(kwh))**2)
r_squared = 1 - (ss_res / ss_tot)

print(f"\n  Throughput rate: {slope:,.0f} kWh/year")
print(f"  Linearity R2: {r_squared:.6f}")
print(f"  Max deviation from linear: {np.max(np.abs(residuals)):,.0f} kWh")

print("\n" + "=" * 70)
print("DATA LOADED SUCCESSFULLY")
print("=" * 70)
print("\nVariables available for Figure 5:")
print("  df_single  - Single-asset trajectory (monthly)")
print("  df_fleet   - Fleet lifespan data")

"""
Cell X (DROP-IN REPLACEMENT):
Figure 5: Strawman comparison calibrated to TRUE SAGE EOL (Best option)
======================================================================

What this cell fixes:
- Uses the actual SAGE EOL crossing (SoH == SoH_EOL) rather than an arbitrary plot horizon.
- Calibrates BOTH strawmen (linear and throughput-only) to hit the SAME endpoint as SAGE at EOL.
- Plots panel (a) out to the SAGE EOL time so all three curves meet at the endpoint.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

# =============================================================================
# CONFIGURATION
# =============================================================================

DATA_DIR = Path("/content/drive/MyDrive/SAGE/")

SINGLE_ASSET_FILE = DATA_DIR / "sage_single_asset_trajectory.csv"
FLEET_FILE = DATA_DIR / "sage_fleet_lifespans.csv"

plt.rcParams.update({
    'font.size': 10,
    'font.family': 'sans-serif',
    'axes.labelsize': 11,
    'axes.titlesize': 12,
    'xtick.labelsize': 9,
    'ytick.labelsize': 9,
    'legend.fontsize': 9,
    'figure.dpi': 150,
    'savefig.dpi': 300,
    'savefig.bbox': 'tight',
})

COLOR_SAGE = '#D55E00'       # Vermillion
COLOR_LINEAR = '#0072B2'     # Blue
COLOR_THROUGHPUT = '#009E73' # Teal
COLOR_EOL = '#666666'        # Gray

# System parameters - LOADED FROM CSV, NOT HARDCODED
SOH_EOL = require_param("SoH_EOL")
E_CAP = require_param("capacity_kwh")

# =============================================================================
# LOAD DATA
# =============================================================================

def load_sage_data():
    """Load SAGE output files."""
    print("Loading SAGE data...")

    df_single = pd.read_csv(SINGLE_ASSET_FILE)
    df_fleet = pd.read_csv(FLEET_FILE)

    print(f"  Single-asset: {len(df_single)} rows, last time = {df_single['years'].iloc[-1]:.2f} years")
    print(f"  Fleet: {len(df_fleet)} assets, lifespan range: "
          f"{df_fleet['lifespan_years'].min():.1f}-{df_fleet['lifespan_years'].max():.1f} years")

    return df_single, df_fleet

# =============================================================================
# HELPERS
# =============================================================================

def estimate_sage_eol(years, soh, cumulative_kwh, soh_eol):
    """
    Return (t_eol_years, Q_eol_kwh) by locating/interpolating the first crossing soh <= soh_eol.
    Robust to:
      - exact equality at a row
      - crossing between rows
      - mild floating point noise
    """
    years = np.asarray(years, dtype=float)
    soh = np.asarray(soh, dtype=float)
    cumulative_kwh = np.asarray(cumulative_kwh, dtype=float)

    # If already exactly at/under EOL at last row, still compute first crossing
    idx = np.where(soh <= soh_eol)[0]
    if len(idx) == 0:
        raise ValueError(
            f"SAGE trajectory does NOT reach SoH_EOL={soh_eol} within the file horizon "
            f"(min SoH = {soh.min():.6f}, last SoH = {soh[-1]:.6f})."
        )

    i = int(idx[0])

    # If it hits at the first row, return that
    if i == 0:
        return years[0], cumulative_kwh[0]

    # If it hits exactly at row i (common if you clamp/stop exactly at EOL), return row i
    if np.isclose(soh[i], soh_eol, atol=1e-12):
        return years[i], cumulative_kwh[i]

    # Otherwise interpolate between i-1 and i
    t0, t1 = years[i-1], years[i]
    s0, s1 = soh[i-1], soh[i]
    q0, q1 = cumulative_kwh[i-1], cumulative_kwh[i]

    # s1 should be < s0 typically, so denominator nonzero
    denom = (s1 - s0)
    if abs(denom) < 1e-15:
        # Degenerate case: SoH flat across the interval, fall back to row i
        return years[i], cumulative_kwh[i]

    alpha = (soh_eol - s0) / denom  # should be in [0,1]
    alpha = float(np.clip(alpha, 0.0, 1.0))

    t_eol = t0 + alpha * (t1 - t0)
    q_eol = q0 + alpha * (q1 - q0)
    return t_eol, q_eol

# =============================================================================
# BASELINE MODELS (calibrated to TRUE SAGE EOL)
# =============================================================================

def linear_degradation_model(years, soh_eol, t_eol_years):
    """Linear model: constant %/year degradation, calibrated to hit soh_eol at t_eol_years."""
    rate = (1.0 - soh_eol) / t_eol_years
    soh = 1.0 - rate * years
    return np.clip(soh, soh_eol, 1.0)

def throughput_degradation_model(cumulative_kwh, soh_eol, Q_eol_kwh):
    """Throughput-only model: degradation proportional to cumulative grid-side throughput."""
    k = (1.0 - soh_eol) / Q_eol_kwh
    soh = 1.0 - k * cumulative_kwh
    return np.clip(soh, soh_eol, 1.0)

# =============================================================================
# FIGURE GENERATION
# =============================================================================

def create_figure_5(df_single, df_fleet, save_path=None):
    """
    Create Figure 5: Three-panel strawman comparison calibrated to TRUE SAGE EOL.

    Panel (a): Single-asset trajectory comparison (0 to SAGE EOL)
    Panel (b): Prediction errors vs SAGE (0 to SAGE EOL)
    Panel (c): Fleet lifespan distributions (SAGE fleet + baseline single-asset fit lifespans)
    """

    # Extract data
    years_all = df_single['years'].to_numpy(dtype=float)
    soh_sage_all = df_single['SoH_SAGE_Truth'].to_numpy(dtype=float)
    cumulative_kwh_all = df_single['cumulative_kwh'].to_numpy(dtype=float)

    # True EOL calibration from SAGE trajectory
    t_eol_years, Q_eol_kwh = estimate_sage_eol(years_all, soh_sage_all, cumulative_kwh_all, SOH_EOL)
    print(f"Calibration (TRUE SAGE EOL): t_eol = {t_eol_years:.2f} years, Q_eol = {Q_eol_kwh:,.0f} kWh")

    # Restrict panels (a) and (b) to the SAGE EOL horizon
    mask = years_all <= (t_eol_years + 1e-12)
    years = years_all[mask]
    soh_sage = soh_sage_all[mask]
    cumulative_kwh = cumulative_kwh_all[mask]

    # Baselines calibrated to TRUE SAGE EOL
    soh_linear = linear_degradation_model(years, SOH_EOL, t_eol_years)
    soh_throughput = throughput_degradation_model(cumulative_kwh, SOH_EOL, Q_eol_kwh)

    # =========================================================================
    # CREATE FIGURE
    # =========================================================================

    fig, axes = plt.subplots(1, 3, figsize=(14, 4.5))

    # -------------------------------------------------------------------------
    # Panel (a): Single-Asset Trajectory Comparison
    # -------------------------------------------------------------------------
    ax1 = axes[0]

    ax1.plot(years, soh_linear * 100,
             color=COLOR_LINEAR, linestyle='--', linewidth=2,
             label='Linear (constant %/yr)')

    ax1.plot(years, soh_throughput * 100,
             color=COLOR_THROUGHPUT, linestyle='-.', linewidth=2,
             label='Throughput-only (grid kWh)')

    ax1.plot(years, soh_sage * 100,
             color=COLOR_SAGE, linestyle='-', linewidth=2.5,
             label='SAGE (physics-based)')

    ax1.axhline(SOH_EOL * 100, color=COLOR_EOL, linestyle=':',
                linewidth=1.5, label='EOL threshold')

    ax1.set_xlabel('Years')
    ax1.set_ylabel('State of Health (%)')
    ax1.set_xlim([0, t_eol_years * 1.02])
    ax1.set_ylim([65, 102])
    ax1.legend(loc='lower left', framealpha=0.95)
    ax1.set_title('(a) Single-Asset Degradation Trajectories')
    ax1.grid(True, alpha=0.3)

    # -------------------------------------------------------------------------
    # Panel (b): Prediction Errors
    # -------------------------------------------------------------------------
    ax2 = axes[1]

    error_linear = (soh_linear - soh_sage) * 100
    error_throughput = (soh_throughput - soh_sage) * 100

    ax2.plot(years, error_linear,
             color=COLOR_LINEAR, linestyle='--', linewidth=2,
             label='Linear - SAGE')

    ax2.plot(years, error_throughput,
             color=COLOR_THROUGHPUT, linestyle='-.', linewidth=2,
             label='Throughput - SAGE')

    ax2.axhline(0, color=COLOR_EOL, linestyle=':', linewidth=1)

    ax2.set_xlabel('Years')
    ax2.set_ylabel('SoH Error (%-points)')
    ax2.set_xlim([0, t_eol_years * 1.02])
    ax2.legend(loc='best', framealpha=0.95)
    ax2.set_title('(b) Prediction Error vs. SAGE')
    ax2.grid(True, alpha=0.3)

    # Shaded regions (Linear error magnitude)
    ax2.fill_between(years, 0, error_linear,
                     where=(error_linear > 0), alpha=0.15, color=COLOR_LINEAR)
    ax2.fill_between(years, 0, error_linear,
                     where=(error_linear < 0), alpha=0.15, color=COLOR_LINEAR)

    # -------------------------------------------------------------------------
    # Panel (c): Fleet Lifespan Distributions
    # -------------------------------------------------------------------------
    ax3 = axes[2]

    sage_lifespans = df_fleet['lifespan_years'].to_numpy(dtype=float)

    ax3.hist(sage_lifespans, bins=20, density=True,
             color=COLOR_SAGE, alpha=0.75, edgecolor='white',
             label=f'SAGE (n={len(sage_lifespans)})')

    # Baseline predicted lifespans (single-asset fit -> zero variance)
    baseline_life_linear = t_eol_years
    baseline_life_throughput = t_eol_years

    ax3.axvline(baseline_life_linear, color=COLOR_LINEAR, linestyle='--',
                linewidth=3, label='Linear baseline (single-asset fit)')
    ax3.axvline(baseline_life_throughput, color=COLOR_THROUGHPUT, linestyle='-.',
                linewidth=3, label='Throughput baseline (single-asset fit)')

    life_min = np.floor(np.min(sage_lifespans)) - 0.5
    life_max = np.ceil(np.max(sage_lifespans)) + 0.5
    ax3.set_xlim([life_min, life_max])

    ymax = ax3.get_ylim()[1]
    x0 = baseline_life_linear
    ax3.annotate('Baselines:\nzero variance\n(single-asset fit)',
                 xy=(x0, ymax * 0.4),
                 xytext=(x0 + (life_max - life_min) * 0.12, ymax * 0.62),
                 fontsize=9,
                 arrowprops=dict(arrowstyle='->', color='black', lw=1),
                 bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.8))

    sage_mean = np.mean(sage_lifespans)
    sage_std = np.std(sage_lifespans)
    sage_min = np.min(sage_lifespans)
    sage_max = np.max(sage_lifespans)
    stats_text = (f'SAGE fleet statistics:\n'
                  f'Mean: {sage_mean:.1f} yr\n'
                  f'Std: {sage_std:.2f} yr\n'
                  f'Range: {sage_min:.1f}-{sage_max:.1f} yr')
    ax3.text(0.02, 0.98, stats_text, transform=ax3.transAxes,
             fontsize=8, verticalalignment='top',
             bbox=dict(boxstyle='round', facecolor='white', alpha=0.9))

    ax3.set_xlabel('Lifespan (years)')
    ax3.set_ylabel('Probability Density')
    ax3.legend(loc='upper right', framealpha=0.95)
    ax3.set_title('(c) Fleet Lifespan Distributions')
    ax3.grid(True, alpha=0.3, axis='y')

    plt.tight_layout()

    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        print(f"Figure saved to: {save_path}")

    return fig, axes


def print_comparison_statistics(df_single, df_fleet):
    """Print quantitative statistics for manuscript text (calibrated to TRUE SAGE EOL)."""

    years_all = df_single['years'].to_numpy(dtype=float)
    soh_sage_all = df_single['SoH_SAGE_Truth'].to_numpy(dtype=float)
    cumulative_kwh_all = df_single['cumulative_kwh'].to_numpy(dtype=float)

    t_eol_years, Q_eol_kwh = estimate_sage_eol(years_all, soh_sage_all, cumulative_kwh_all, SOH_EOL)

    mask = years_all <= (t_eol_years + 1e-12)
    years = years_all[mask]
    soh_sage = soh_sage_all[mask]
    cumulative_kwh = cumulative_kwh_all[mask]

    soh_linear = linear_degradation_model(years, SOH_EOL, t_eol_years)
    soh_throughput = throughput_degradation_model(cumulative_kwh, SOH_EOL, Q_eol_kwh)

    error_linear = (soh_linear - soh_sage) * 100
    error_throughput = (soh_throughput - soh_sage) * 100

    print("=" * 60)
    print("STRAWMAN COMPARISON STATISTICS (TRUE SAGE EOL)")
    print("=" * 60)

    print(f"\nSingle-Asset Trajectory:")
    print(f"  SAGE EOL time: {t_eol_years:.2f} years")
    print(f"  Throughput at EOL (grid-side): {Q_eol_kwh:,.0f} kWh")
    print(f"  Equivalent full cycles (grid-side): {Q_eol_kwh / E_CAP:,.0f}")

    print(f"\nLinear Model Errors (0 to EOL):")
    print(f"  Max overestimate: {np.max(error_linear):.2f} %-points")
    print(f"  Max underestimate: {np.min(error_linear):.2f} %-points")
    print(f"  Mean absolute error: {np.mean(np.abs(error_linear)):.2f} %-points")

    print(f"\nThroughput Model Errors (0 to EOL):")
    print(f"  Max overestimate: {np.max(error_throughput):.2f} %-points")
    print(f"  Max underestimate: {np.min(error_throughput):.2f} %-points")
    print(f"  Mean absolute error: {np.mean(np.abs(error_throughput)):.2f} %-points")

    lifespans = df_fleet['lifespan_years'].to_numpy(dtype=float)
    print(f"\nFleet Statistics (n={len(lifespans)}):")
    print(f"  SAGE mean lifespan: {np.mean(lifespans):.2f} years")
    print(f"  SAGE std lifespan: {np.std(lifespans):.2f} years")
    print(f"  SAGE lifespan range: {np.min(lifespans):.1f}-{np.max(lifespans):.1f} years")
    print(f"  Linear baseline predicted lifespan: {t_eol_years:.2f} years (zero variance)")
    print(f"  Throughput baseline predicted lifespan: {t_eol_years:.2f} years (zero variance)")
    print(f"\n  ** Key finding: Baseline models predict ZERO fleet variance **")
    print(f"  ** SAGE captures {np.max(lifespans) - np.min(lifespans):.1f} years of spread **")

    print("=" * 60)

# =============================================================================
# MAIN EXECUTION
# =============================================================================

df_single, df_fleet = load_sage_data()

print("\nGenerating Figure 5 (TRUE SAGE EOL calibration)...")
fig, axes = create_figure_5(
    df_single,
    df_fleet,
    save_path=DATA_DIR / 'Figure_5_strawman_comparison.png'
)

print_comparison_statistics(df_single, df_fleet)

plt.show()

print("\nDone!")

# Extract data again
years = df_single['years'].values
soh_sage = df_single['SoH_SAGE_Truth'].values
cumulative_kwh = df_single['cumulative_kwh'].values

# Calibration points
sage_eol_years = years[-1]
sage_eol_throughput = cumulative_kwh[-1]

# Baseline predictions
soh_linear = linear_degradation_model(years, SOH_EOL, sage_eol_years)
soh_throughput = throughput_degradation_model(
    cumulative_kwh, SOH_EOL, sage_eol_throughput
)

# Errors
error_linear = (soh_linear - soh_sage) * 100
error_throughput = (soh_throughput - soh_sage) * 100

# Inspect year 8
idx = np.argmin(np.abs(years - 8))
print("Year:", years[idx])
print("Linear error:", error_linear[idx])
print("Throughput error:", error_throughput[idx])